# Government Schemes — Feature Engineering & Dataset Integration

## Objective

This notebook integrates the Hugging Face and GitHub government schemes datasets into a unified AI-ready dataset for the Agentic AI government scheme discovery system.

The workflow includes:

- Standardizing the two datasets
- Identifying overlapping schemes
- Matching and merging scheme records
- Preserving complementary information from both sources
- Creating normalized government, geographic, category, beneficiary, and eligibility features
- Combining structured and unstructured eligibility information
- Creating a unified semantic representation for RAG
- Preserving source provenance
- Removing redundant and EDA-only features
- Validating the final dataset
- Saving the final AI-ready government schemes dataset

The final dataset will be designed to support both:
1. Structured filtering and agentic decision-making
2. Semantic retrieval and RAG-based question answering

In [1]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 100)

In [2]:
# Load Hugging Face dataset
hf_df = pd.read_csv("/content/Schemes.csv")

# Load GitHub dataset
github_df = pd.read_csv("/content/gov_myscheme_data.csv")

print("Hugging Face dataset shape:", hf_df.shape)
print("GitHub dataset shape:", github_df.shape)

Hugging Face dataset shape: (4693, 24)
GitHub dataset shape: (2066, 16)

In [3]:
print("HUGGING FACE DATASET")
print("=" * 50)
print(hf_df.columns.tolist())

print("\nGITHUB DATASET")
print("=" * 50)
print(github_df.columns.tolist())

HUGGING FACE DATASET
==================================================
['slug', 'name', 'description', 'ministry', 'department', 'state', 'category', 'beneficiary_type', 'benefits', 'eligibility_text', 'application_process', 'documents_required', 'apply_url', 'official_url', 'eligibility_age_min', 'eligibility_age_max', 'eligibility_gender', 'eligibility_caste', 'eligibility_income_max', 'eligibility_residence', 'eligibility_state', 'eligibility_disability', 'eligibility_bpl', 'scraped_at']

GITHUB DATASET
==================================================
['Scheme Name', 'Scheme Slug', 'Level', 'State / UT / Ministry', 'Application Mode', 'Tags / Categories', 'Description', 'Eligibility Criteria', 'Eligibility (General)', 'Exclusions / Ineligibility', 'Benefits', 'Application Process', 'Documents Required', 'Frequently Asked Questions (FAQs)', 'Official Link', 'MyScheme URL']

In [5]:
hf_slugs = set(hf_df["slug"].dropna().astype(str).str.strip().str.lower())
github_slugs = set(github_df["Scheme Slug"].dropna().astype(str).str.strip().str.lower())

common_slugs = hf_slugs.intersection(github_slugs)

print("Hugging Face schemes:", len(hf_slugs))
print("GitHub schemes:", len(github_slugs))
print("Exact slug matches:", len(common_slugs))
print("HF-only schemes:", len(hf_slugs - github_slugs))
print("GitHub-only schemes:", len(github_slugs - hf_slugs))

Hugging Face schemes: 4693
GitHub schemes: 2066
Exact slug matches: 1895
HF-only schemes: 2798
GitHub-only schemes: 171

In [6]:
matched_slugs = list(common_slugs)

slug_match_df = pd.merge(
    hf_df[["slug", "name"]],
    github_df[["Scheme Slug", "Scheme Name"]],
    left_on=hf_df["slug"].astype(str).str.strip().str.lower(),
    right_on=github_df["Scheme Slug"].astype(str).str.strip().str.lower(),
    how="inner"
)

slug_match_df = slug_match_df.rename(columns={
    "name": "HF Name",
    "Scheme Name": "GitHub Name"
})

slug_match_df[["HF Name", "GitHub Name", "slug", "Scheme Slug"]].head(20)

,HF Name,GitHub Name,slug,Scheme Slug
0,"""Immediate Relief Assistance"" under ""Welfare and Relief for Fishermen During Lean Seasons and N...","""Immediate Relief Assistance"" under ""Welfare and Relief for Fishermen During Lean Seasons and Na...",ira-wrflsncs,ira-wrflsncs
1,AICTE SHORT TERM TRAINING PROGRAMME-SFURTI SCHEME,AICTE SHORT TERM TRAINING PROGRAMME-SFURTI SCHEME,astpss,astpss
2,Consortia & Tender Marketing Scheme,Consortia & Tender Marketing Scheme,ctms,ctms
3,Indira Mahila Shakti Udyam Protsahan Yojana,Indira Mahila Shakti Udyam Protsahan Yojana,imspesy,imspesy
4,Nirman Shramik Jeevan va Bhavishya Suraksha Yojana,Nirman Shramik Jeevan Bhavishya Suraksha Yojana,nsjbsy,nsjbsy
5,Safai Karmakaar Ke Putr/Putri Hetu Vishesh Coaching Yojana,Safai Karmakaar Ke Putr/Putri Hetu Vishesh Coaching Yojana,skhvc,skhvc
6,"'Financial Assistance for Setting Up of Sales Emporia by Industrial Associations, Handicrafts So...","'Financial Assistance for Setting Up of Sales Emporia by Industrial Associations, Handicrafts So...",fasuseiahsri-mp,fasuseiahsri-mp
7,"'Grant-in-Aid to Industrial Association, CII, Industrial NGOs for Promotion of SME Clusters' und...","'Grant-in-Aid to Industrial Association, CII, Industrial NGOs for Promotion of SME Clusters' und...",giaiacinpsc,giaiacinpsc
8,"'Organizing/ Participation in Exhibitions /Trade Fairs /Expo /Seminars /Investors Meets, etc' un...","'Organizing/ Participation in Exhibitions /Trade Fairs /Expo /Seminars /Investors Meets, etc' un...",opetfesime-mp,opetfesime-mp
9,'Rent Subsidy for Sales Emporia Established by Handicrafts / Micro & Small Industries Emporium' ...,'Rent Subsidy for Sales Emporia Established by Handicrafts / Micro & Small Industries Emporium' ...,rsseehmsie-mp,rsseehmsie-mp
10,"""Advance / High Skill Training"" Component of the ""Development of Industries"" Scheme","""Advance / High Skill Training"" Component of the ""Development of Industries"" Scheme",ahst,ahst
11,"""Advance/High Skill Training in Coir"" Component of the ""Development of Coir"" Scheme","""Advance/High Skill Training in Coir"" Component of the ""Development of Coir"" Scheme",ahstc-dc,ahstc-dc
12,"""Advanced Training in Handicrafts"" Component of the ""Development of Handicrafts"" Scheme","""Advanced Training in Handicrafts"" Component of the ""Development of Handicrafts"" Scheme",atihcdohs,atihcdohs
13,"""Annual Insurance Premium for Boat Owners"" under ""Financial Assistance for Availing Subsidy Comp...","""Annual Insurance Premium for Boat Owners"" under ""Financial Assistance for Availing Subsidy Comp...",aipbo-faascdmf,aipbo-faascdmf
14,"""Assistance for Energy and Water Conservation"" under ""Motivation of Entrepreneurs to Start Indus...","""Assistance for Energy and Water Conservation"" under ""Motivation of Entrepreneurs to Start Indus...",aewc-mesifai-vi,aewc-mesifai-vi
15,"""Assistance for Intellectual Property Protection Support"" under ""Motivation of Entrepreneurs to ...","""Assistance for Intellectual Property Protection Support"" under ""Motivation of Entrepreneurs to ...",aipps-mesifai-vi,aipps-mesifai-vi
16,"""Assistance for Technology Acquisition"" under ""Motivation of Entrepreneurs to Start Industries a...","""Assistance for Technology Acquisition"" under ""Motivation of Entrepreneurs to Start Industries a...",ata-mesifa-cii,ata-mesifa-cii
17,"""Capital Investment Subsidy (for New and Existing Industries)"" under ""Motivation of Entrepreneur...","""Capital Investment Subsidy (for New and Existing Industries)"" under ""Motivation of Entrepreneur...",cis-mesifa-cii,cis-mesifa-cii
18,"""Capital Investment Subsidy: 5% Additional Capital Investment Subsidy to Karaikal Region"" under ...","""Capital Investment Subsidy: 5% Additional Capital Investment Subsidy to Karaikal Region"" under ...",cis5aciskr-mesifai,cis5aciskr-mesifai
19,"""Capital Investment Subsidy: Information Technology (IT) / Information Technology Enabled Servic...","""Capital Investment Subsidy: Information Technology (IT) / Information Technology Enabled Servic...",cisitites-mesifai,cisitites-mesifai

In [7]:
import re

def normalize_scheme_name(text):
    if pd.isna(text):
        return ""

    text = str(text).lower().strip()

    # Normalize common punctuation
    text = re.sub(r"[^a-z0-9\s]", " ", text)

    # Normalize whitespace
    text = re.sub(r"\s+", " ", text).strip()

    return text


hf_df["name_normalized"] = hf_df["name"].apply(normalize_scheme_name)
github_df["name_normalized"] = github_df["Scheme Name"].apply(normalize_scheme_name)

print("HF normalized names created:", hf_df["name_normalized"].notna().sum())
print("GitHub normalized names created:", github_df["name_normalized"].notna().sum())

HF normalized names created: 4693
GitHub normalized names created: 2066

In [8]:
# Identify schemes that did not match by slug
hf_unmatched = hf_df[
    ~hf_df["slug"].astype(str).str.strip().str.lower().isin(common_slugs)
].copy()

github_unmatched = github_df[
    ~github_df["Scheme Slug"].astype(str).str.strip().str.lower().isin(common_slugs)
].copy()

# Find exact matches using normalized scheme names
name_matches = pd.merge(
    hf_unmatched[["slug", "name", "name_normalized"]],
    github_unmatched[["Scheme Slug", "Scheme Name", "name_normalized"]],
    on="name_normalized",
    how="inner"
)

print("HF-only records:", len(hf_unmatched))
print("GitHub-only records:", len(github_unmatched))
print("Additional exact normalized-name matches:", len(name_matches))

name_matches[[
    "name",
    "Scheme Name",
    "slug",
    "Scheme Slug"
]].head(20)

HF-only records: 2798
GitHub-only records: 171
Additional exact normalized-name matches: 2

,name,Scheme Name,slug,Scheme Slug
0,Devnarayan Gurukul Yojana,Devnarayan Gurukul Yojana,dgyr,dgy
1,National Agriculture Insurance Scheme,National Agriculture Insurance Scheme,nai,nais

In [9]:
# Create confirmed scheme matches

slug_matches = pd.DataFrame({
    "hf_slug": list(common_slugs),
    "github_slug": list(common_slugs),
    "match_type": "exact_slug"
})

name_matches_confirmed = name_matches.rename(columns={
    "slug": "hf_slug",
    "Scheme Slug": "github_slug"
})[[
    "hf_slug",
    "github_slug"
]].copy()

name_matches_confirmed["match_type"] = "exact_normalized_name"

confirmed_matches = pd.concat(
    [slug_matches, name_matches_confirmed],
    ignore_index=True
).drop_duplicates(subset=["hf_slug", "github_slug"])

print("Confirmed matched scheme pairs:", len(confirmed_matches))
print("\nMatch types:")
print(confirmed_matches["match_type"].value_counts())

Confirmed matched scheme pairs: 1897

Match types:
match_type
exact_slug               1895
exact_normalized_name       2
Name: count, dtype: int64

In [10]:
# Inspect information availability for the confirmed overlapping schemes

hf_matched = hf_df[
    hf_df["slug"].astype(str).str.strip().str.lower().isin(
        confirmed_matches["hf_slug"]
    )
].copy()

github_matched = github_df[
    github_df["Scheme Slug"].astype(str).str.strip().str.lower().isin(
        confirmed_matches["github_slug"]
    )
].copy()

print("Matched HF records:", len(hf_matched))
print("Matched GitHub records:", len(github_matched))

print("\nHF columns with missing values:")
print(hf_matched.isna().sum().sort_values(ascending=False))

print("\nGitHub columns with missing values:")
print(github_matched.isna().sum().sort_values(ascending=False))

Matched HF records: 1897
Matched GitHub records: 1897

HF columns with missing values:
eligibility_age_max       1553
eligibility_income_max    1549
ministry                  1451
eligibility_age_min       1431
department                 167
beneficiary_type            43
apply_url                    5
documents_required           4
benefits                     1
description                  1
eligibility_text             1
application_process          1
category                     1
state                        0
name                         0
slug                         0
official_url                 0
eligibility_gender           0
eligibility_caste            0
eligibility_residence        0
eligibility_state            0
eligibility_disability       0
eligibility_bpl              0
scraped_at                   0
name_normalized              0
dtype: int64

GitHub columns with missing values:
Exclusions / Ineligibility           1564
Tags / Categories                       5
Documents Required                      2
Eligibility (General)                   1
Scheme Name                             0
Application Mode                        0
State / UT / Ministry                   0
Scheme Slug                             0
Level                                   0
Eligibility Criteria                    0
Description                             0
Benefits                                0
Application Process                     0
Frequently Asked Questions (FAQs)       0
Official Link                           0
MyScheme URL                            0
name_normalized                         0
dtype: int64

In [11]:
github_clean = github_df.rename(columns={
    "Scheme Name": "scheme_name",
    "Scheme Slug": "scheme_slug",
    "Level": "government_level",
    "State / UT / Ministry": "state_ut_ministry",
    "Application Mode": "application_mode",
    "Tags / Categories": "raw_tags",
    "Description": "description",
    "Eligibility Criteria": "eligibility_criteria",
    "Eligibility (General)": "eligibility_general",
    "Exclusions / Ineligibility": "exclusion_text",
    "Benefits": "benefits",
    "Application Process": "application_process",
    "Documents Required": "documents_required",
    "Frequently Asked Questions (FAQs)": "faqs",
    "Official Link": "official_url_github",
    "MyScheme URL": "myscheme_url"
}).copy()

print("GitHub columns after standardization:")
print(github_clean.columns.tolist())

GitHub columns after standardization:
['scheme_name', 'scheme_slug', 'government_level', 'state_ut_ministry', 'application_mode', 'raw_tags', 'description', 'eligibility_criteria', 'eligibility_general', 'exclusion_text', 'benefits', 'application_process', 'documents_required', 'faqs', 'official_url_github', 'myscheme_url', 'name_normalized']

In [12]:
hf_clean = hf_df.rename(columns={
    "slug": "scheme_slug",
    "name": "scheme_name",
    "description": "description",
    "ministry": "ministry_hf",
    "department": "department",
    "state": "state_hf",
    "category": "category_hf",
    "beneficiary_type": "beneficiary_type_hf",
    "benefits": "benefits_hf",
    "eligibility_text": "eligibility_text_hf",
    "application_process": "application_process_hf",
    "documents_required": "documents_required_hf",
    "apply_url": "apply_url",
    "official_url": "official_url_hf",
    "eligibility_age_min": "age_min",
    "eligibility_age_max": "age_max",
    "eligibility_gender": "gender_eligibility",
    "eligibility_caste": "caste_category",
    "eligibility_income_max": "income_max",
    "eligibility_residence": "residence_requirement",
    "eligibility_state": "eligibility_state",
    "eligibility_disability": "disability_eligibility",
    "eligibility_bpl": "bpl_required",
    "scraped_at": "scraped_at"
}).copy()

print("Hugging Face columns after standardization:")
print(hf_clean.columns.tolist())

Hugging Face columns after standardization:
['scheme_slug', 'scheme_name', 'description', 'ministry_hf', 'department', 'state_hf', 'category_hf', 'beneficiary_type_hf', 'benefits_hf', 'eligibility_text_hf', 'application_process_hf', 'documents_required_hf', 'apply_url', 'official_url_hf', 'age_min', 'age_max', 'gender_eligibility', 'caste_category', 'income_max', 'residence_requirement', 'eligibility_state', 'disability_eligibility', 'bpl_required', 'scraped_at', 'name_normalized']

In [13]:
# Create clean scheme IDs for merging

hf_clean["scheme_id"] = (
    hf_clean["scheme_slug"]
    .astype(str)
    .str.strip()
    .str.lower()
)

github_clean["scheme_id"] = (
    github_clean["scheme_slug"]
    .astype(str)
    .str.strip()
    .str.lower()
)

# Check uniqueness
print("HF unique scheme IDs:", hf_clean["scheme_id"].nunique())
print("HF total records:", len(hf_clean))

print("\nGitHub unique scheme IDs:", github_clean["scheme_id"].nunique())
print("GitHub total records:", len(github_clean))

HF unique scheme IDs: 4693
HF total records: 4693

GitHub unique scheme IDs: 2066
GitHub total records: 2066

In [14]:
merged_df = hf_clean.merge(
    github_clean,
    on="scheme_id",
    how="outer",
    suffixes=("_hf", "_github"),
    indicator=True
)

print("Merged dataset shape:", merged_df.shape)

print("\nMerge status:")
print(merged_df["_merge"].value_counts())

Merged dataset shape: (4864, 44)

Merge status:
_merge
left_only     2798
both          1895
right_only     171
Name: count, dtype: int64

In [15]:
matched_preview = merged_df[
    merged_df["_merge"] == "both"
][[
    "scheme_id",
    "scheme_name_hf",
    "scheme_name_github",
    "scheme_slug_hf",
    "scheme_slug_github"
]].head(20)

matched_preview

,scheme_id,scheme_name_hf,scheme_name_github,scheme_slug_hf,scheme_slug_github
3,25-ciss,25% Capital Investment Subsidy Scheme,25% Capital Investment Subsidy Scheme,25-ciss,25-ciss
4,40shydcs,"40% Subsidy On Hank Yarn, Dyes & Chemicals Scheme","40% Subsidy On Hank Yarn, Dyes & Chemicals Scheme",40shydcs,40shydcs
8,a-gainer,AICTE - Grant For Augmenting Infrastructure In North Eastern Region,AICTE - Grant For Augmenting Infrastructure In North Eastern Region,a-gainer,a-gainer
9,a-pudu,ARAVANAIPPU,ARAVANAIPPU,a-pudu,a-pudu
10,a2ks,Access to Knowledge for Technology Development and Dissemination (A2K+),Access To Knowledge For Technology Development And Dissemination (A2K+) - Studies,a2ks,a2ks
13,aabcs,Annal Ambedkar Business Champions Scheme,Annal Ambedkar Business Champions Scheme,aabcs,aabcs
15,aaby,Aam Aadmi Bima Yojana,Aam Aadmi Bima Yojana,aaby,aaby
18,aaelss,Assam Abhinandan Education Loan Subsidy Scheme,Assam Abhinandan Education Loan Subsidy Scheme,aaelss,aaelss
20,aag,Aponar Apon Ghar,Aponar Apon Ghar,aag,aag
22,aamgsiscs,Award of Adhoc Merit Grant (Special Incentive) to Scheduled Caste Students,Award of Adhoc Merit Grant (Special Incentive) to Scheduled Caste Students,aamgsiscs,aamgsiscs
23,aan,Assam Arogya Nidhi Scheme,Assam Arogya Nidhi Scheme,aan,aan
27,aas,Ashraya Adhar Scheme,Ashraya Adhar Scheme,aas,aas
28,aasfsv,Aushadhi Avam Sugandhit Fasal Shetra Vistar,Aushadhi Avam Sugandhit Fasal Shetra Vistar,aasfsv,aasfsv
30,aasra,AASRA Scheme,AASRA Scheme,aasra,aasra
31,aass,Agriculture Academic Studies Scheme,Agriculture Academic Studies Scheme,aass,aass
32,aavy,Atal Awasiya Vidyala Yojana,Atal Awasiya Vidyala Yojana,aavy,aavy
34,aay-goa,Atal Asra Yojana,Atal Asra Yojana,aay-goa,aay-goa
40,abhb,Aapki Beti Hamari Beti,Aapki Beti Hamari Beti,abhb,abhb
41,abn,Anti Bird Net,Anti Bird Net,abn,abn
44,absy,Aaws Bhatta Sahayata Yojana,Aaws Bhatta Sahayata Yojana,absy,absy

In [16]:
name_match_ids = ["dgyr", "nai"]

name_match_review = hf_clean[
    hf_clean["scheme_id"].isin(name_match_ids)
][[
    "scheme_id",
    "scheme_name",
    "scheme_slug",
    "name_normalized"
]].merge(
    github_clean[[
        "scheme_id",
        "scheme_name",
        "scheme_slug",
        "name_normalized"
    ]],
    on="name_normalized",
    how="inner",
    suffixes=("_hf", "_github")
)

name_match_review

,scheme_id_hf,scheme_name_hf,scheme_slug_hf,name_normalized,scheme_id_github,scheme_name_github,scheme_slug_github
0,dgyr,Devnarayan Gurukul Yojana,dgyr,devnarayan gurukul yojana,dgy,Devnarayan Gurukul Yojana,dgy
1,nai,National Agriculture Insurance Scheme,nai,national agriculture insurance scheme,nais,National Agriculture Insurance Scheme,nais

In [17]:
name_match_mapping = {
    "dgy": "dgyr",
    "nais": "nai"
}

print("Confirmed name-based matches:", len(name_match_mapping))
print(name_match_mapping)

Confirmed name-based matches: 2
{'dgy': 'dgyr', 'nais': 'nai'}

In [18]:
# Create unified IDs for the two confirmed name-based matches

github_clean["unified_scheme_id"] = github_clean["scheme_id"].replace(
    name_match_mapping
)

hf_clean["unified_scheme_id"] = hf_clean["scheme_id"]

print("HF unique unified IDs:", hf_clean["unified_scheme_id"].nunique())
print("GitHub unique unified IDs:", github_clean["unified_scheme_id"].nunique())

HF unique unified IDs: 4693
GitHub unique unified IDs: 2066

In [19]:
merged_df = hf_clean.merge(
    github_clean,
    on="unified_scheme_id",
    how="outer",
    suffixes=("_hf", "_github"),
    indicator=True
)

print("Unified merged dataset shape:", merged_df.shape)

print("\nMerge status:")
print(merged_df["_merge"].value_counts())

Unified merged dataset shape: (4862, 46)

Merge status:
_merge
left_only     2796
both          1897
right_only     169
Name: count, dtype: int64

In [20]:
print("Number of columns:", len(merged_df.columns))

for i, col in enumerate(merged_df.columns, start=1):
    print(f"{i:02d}. {col}")

Number of columns: 46
01. scheme_slug_hf
02. scheme_name_hf
03. description_hf
04. ministry_hf
05. department
06. state_hf
07. category_hf
08. beneficiary_type_hf
09. benefits_hf
10. eligibility_text_hf
11. application_process_hf
12. documents_required_hf
13. apply_url
14. official_url_hf
15. age_min
16. age_max
17. gender_eligibility
18. caste_category
19. income_max
20. residence_requirement
21. eligibility_state
22. disability_eligibility
23. bpl_required
24. scraped_at
25. name_normalized_hf
26. scheme_id_hf
27. unified_scheme_id
28. scheme_name_github
29. scheme_slug_github
30. government_level
31. state_ut_ministry
32. application_mode
33. raw_tags
34. description_github
35. eligibility_criteria
36. eligibility_general
37. exclusion_text
38. benefits
39. application_process
40. documents_required
41. faqs
42. official_url_github
43. myscheme_url
44. name_normalized_github
45. scheme_id_github
46. _merge

In [21]:
# Canonical scheme name
merged_df["scheme_name"] = (
    merged_df["scheme_name_hf"]
    .combine_first(merged_df["scheme_name_github"])
)

# Canonical scheme slug
merged_df["scheme_slug"] = (
    merged_df["scheme_slug_hf"]
    .combine_first(merged_df["scheme_slug_github"])
)

# Unified scheme ID is already our canonical merge identifier
merged_df["scheme_id"] = merged_df["unified_scheme_id"]

print("Missing scheme names:", merged_df["scheme_name"].isna().sum())
print("Missing scheme slugs:", merged_df["scheme_slug"].isna().sum())
print("Missing scheme IDs:", merged_df["scheme_id"].isna().sum())

print("\nUnique scheme IDs:", merged_df["scheme_id"].nunique())
print("Total records:", len(merged_df))

Missing scheme names: 0
Missing scheme slugs: 0
Missing scheme IDs: 0

Unique scheme IDs: 4862
Total records: 4862

In [23]:
# Normalize GitHub government level
government_level_github = (
    merged_df["government_level"]
    .astype("string")
    .str.strip()
    .str.lower()
)

# Start with the explicit GitHub value
merged_df["government_level_unified"] = government_level_github.replace({
    "state/ut": "State/UT",
    "central": "Central"
})

# Normalize HF state field
hf_state = (
    merged_df["state_hf"]
    .astype("string")
    .str.strip()
    .str.lower()
)

# Derive government level only for records where GitHub level is missing
hf_derived_level = pd.Series(pd.NA, index=merged_df.index, dtype="string")

hf_derived_level.loc[hf_state == "central"] = "Central"
hf_derived_level.loc[
    hf_state.notna() & (hf_state != "central")
] = "State/UT"

# Fill only missing GitHub-derived values
merged_df["government_level_unified"] = (
    merged_df["government_level_unified"]
    .fillna(hf_derived_level)
)

print(merged_df["government_level_unified"].value_counts(dropna=False))

government_level_unified
State/UT                 2559
state / ut government    1539
central government        527
Central                   237
Name: count, dtype: Int64

In [24]:
# Normalize government level values from GitHub
government_level_github = (
    merged_df["government_level"]
    .astype("string")
    .str.strip()
    .str.lower()
)

# Map all observed variants to a single standard representation
merged_df["government_level_unified"] = government_level_github.map({
    "state/ut": "State/UT",
    "state / ut government": "State/UT",
    "central": "Central",
    "central government": "Central"
})

# For HF-only records, derive the level from state_hf
hf_state = (
    merged_df["state_hf"]
    .astype("string")
    .str.strip()
    .str.lower()
)

hf_derived_level = pd.Series(
    pd.NA,
    index=merged_df.index,
    dtype="string"
)

hf_derived_level.loc[hf_state == "central"] = "Central"
hf_derived_level.loc[
    hf_state.notna() & (hf_state != "central")
] = "State/UT"

# Fill missing GitHub values using HF-derived values
merged_df["government_level_unified"] = (
    merged_df["government_level_unified"]
    .fillna(hf_derived_level)
)

print(merged_df["government_level_unified"].value_counts(dropna=False))

government_level_unified
State/UT    4098
Central      764
Name: count, dtype: int64

In [25]:
# Create unified State/UT field
github_state_value = (
    merged_df["state_ut_ministry"]
    .astype("string")
    .str.strip()
)

hf_state_value = (
    merged_df["state_hf"]
    .astype("string")
    .str.strip()
)

# Use GitHub state value for State/UT schemes
merged_df["state_ut"] = pd.NA

state_mask = merged_df["government_level_unified"] == "State/UT"

merged_df.loc[state_mask, "state_ut"] = (
    github_state_value[state_mask]
    .fillna(hf_state_value[state_mask])
)

# For Central schemes, state_ut should remain missing
merged_df["state_ut"] = merged_df["state_ut"].astype("string")

print("Missing state_ut:", merged_df["state_ut"].isna().sum())

print("\nState/UT values:")
print(merged_df.loc[state_mask, "state_ut"].value_counts().head(40))

Missing state_ut: 764

State/UT values:
state_ut
Gujarat                                     639
Uttarakhand                                 448
Madhya Pradesh                              286
Goa                                         272
Puducherry                                  270
Haryana                                     246
Tamil Nadu                                  232
Rajasthan                                   158
Bihar                                       113
West Bengal                                 112
Chhattisgarh                                107
Jharkhand                                    95
Odisha                                       89
Maharashtra                                  85
Meghalaya                                    84
Assam                                        82
Kerala                                       81
Himachal Pradesh                             71
Andhra Pradesh                               65
Karnataka                                    64
Dadra & Nagar Haveli and Daman & Diu         61
Delhi                                        53
Jammu and Kashmir                            44
Uttar Pradesh                                44
Punjab                                       41
Tripura                                      40
Arunachal Pradesh                            39
Mizoram                                      28
Manipur                                      27
Telangana                                    25
Sikkim                                       24
Nagaland                                     20
Chandigarh                                   20
Andaman and Nicobar Islands                  19
Lakshadweep                                   9
Ladakh                                        4
Dadra and Nagar Haveli and Daman and Diu      1
Name: count, dtype: Int64

In [26]:
# Create unified ministry field
hf_ministry = (
    merged_df["ministry_hf"]
    .astype("string")
    .str.strip()
)

github_ministry = (
    merged_df["state_ut_ministry"]
    .astype("string")
    .str.strip()
)

merged_df["ministry"] = hf_ministry

# For missing ministry values, use the GitHub value only for Central schemes
central_mask = merged_df["government_level_unified"] == "Central"

merged_df.loc[central_mask, "ministry"] = (
    merged_df.loc[central_mask, "ministry"]
    .fillna(github_ministry[central_mask])
)

merged_df["ministry"] = merged_df["ministry"].astype("string")

print("Missing ministry:", merged_df["ministry"].isna().sum())

print("\nTop ministry values:")
print(merged_df["ministry"].value_counts().head(20))

Missing ministry: 4098

Top ministry values:
ministry
Ministry of Education                                  90
Ministry Of Social Justice and Empowerment             84
Ministry Of Science And Technology                     64
Ministry Of Commerce And Industry                      47
Ministry Of Agriculture and Farmers Welfare            41
Ministry Of Micro, Small and Medium Enterprises        30
Ministry of Social Justice and Empowerment             27
Ministry Of Textiles                                   24
Ministry of Electronics and Information Technology     24
Ministry Of Home Affairs                               18
Ministry Of Finance                                    18
Ministry Of Culture                                    15
Ministry Of Health & Family Welfare                    15
Ministry Of Defence                                    15
Ministry of Women and Child Development                13
Ministry Of Labour and Employment                      13
Ministry of Fisheries,Animal Husbandry and Dairying    13
Ministry Of Minority Affairs                           12
Ministry Of Youth Affairs & Sports                     11
Ministry Of Communication                              11
Name: count, dtype: Int64

In [27]:
hf_ministry = merged_df["ministry_hf"].astype("string").str.strip()
github_ministry = merged_df["state_ut_ministry"].astype("string").str.strip()
central_mask = merged_df["government_level_unified"] == "Central"
merged_df["ministry"] = hf_ministry
merged_df.loc[central_mask, "ministry"] = merged_df.loc[central_mask, "ministry"].fillna(github_ministry[central_mask])
merged_df["ministry"] = merged_df["ministry"].astype("string")

print("Missing ministry:", merged_df["ministry"].isna().sum())
print("\nTop ministry values:")
print(merged_df["ministry"].value_counts().head(20))

Missing ministry: 4098

Top ministry values:
ministry
Ministry of Education                                  90
Ministry Of Social Justice and Empowerment             84
Ministry Of Science And Technology                     64
Ministry Of Commerce And Industry                      47
Ministry Of Agriculture and Farmers Welfare            41
Ministry Of Micro, Small and Medium Enterprises        30
Ministry of Social Justice and Empowerment             27
Ministry Of Textiles                                   24
Ministry of Electronics and Information Technology     24
Ministry Of Home Affairs                               18
Ministry Of Finance                                    18
Ministry Of Culture                                    15
Ministry Of Health & Family Welfare                    15
Ministry Of Defence                                    15
Ministry of Women and Child Development                13
Ministry Of Labour and Employment                      13
Ministry of Fisheries,Animal Husbandry and Dairying    13
Ministry Of Minority Affairs                           12
Ministry Of Youth Affairs & Sports                     11
Ministry Of Communication                              11
Name: count, dtype: Int64

In [28]:
merged_df["ministry"] = merged_df["ministry"].str.replace(r"\s+", " ", regex=True).str.strip()
print("Central schemes with ministry:", merged_df.loc[central_mask, "ministry"].notna().sum())
print("Central schemes without ministry:", merged_df.loc[central_mask, "ministry"].isna().sum())

Central schemes with ministry: 762
Central schemes without ministry: 2

In [29]:
print(merged_df.loc[central_mask & merged_df["ministry"].isna(), ["scheme_name", "state_ut_ministry", "scheme_slug_github"]])

                                                                            scheme_name  \
4708  Vanchit Ikai Samooh aur Vargon ki Aarthik Sahayata Yojana (VISVAS) for Individual
4718                                                      Varishtha Pension Bima Yojana

     state_ut_ministry scheme_slug_github
4708               NaN                NaN
4718               NaN                NaN

In [30]:
print(merged_df.loc[central_mask & merged_df["ministry"].isna(), ["scheme_name", "scheme_slug_hf", "description_hf", "ministry_hf"]].to_string(index=False))

                                                                      scheme_name scheme_slug_hf description_hf ministry_hf
Vanchit Ikai Samooh aur Vargon ki Aarthik Sahayata Yojana (VISVAS) for Individual        visvasi            NaN         NaN
                                                    Varishtha Pension Bima Yojana           vpby            NaN         NaN

In [31]:
merged_df["department_unified"] = merged_df["department"].astype("string").str.strip()
print("Missing department:", merged_df["department_unified"].isna().sum())
print("Unique departments:", merged_df["department_unified"].nunique())

Missing department: 462
Unique departments: 376

In [32]:
print(merged_df["department_unified"].value_counts().head(20))

department_unified
Labour Department                                           266
Agriculture, Farmers Welfare and Cooperation Department     222
Social Justice and Empowerment Department                   210
Agriculture Department                                      173
Social Welfare Department                                   130
Industries and Mines Department                             116
Labour and Employment Department                             84
Art, Culture and Museums Department                          80
Industries and Commerce Department, Puducherry               74
Department Of Higher Education                               71
Women and Child Development Department                       67
Fisheries Department                                         62
Tourism Department                                           61
Education Department                                         59
Higher Education Department                                  57
Social Justice and Special Assistance Department             56
Department of Social Justice & Empowerment                   52
Welfare of Differently Abled Persons Department              48
Sports, Youth and Cultural Activities Department             46
Welfare of Scheduled Caste & Backward Classes Department     46
Name: count, dtype: Int64

In [33]:
print(merged_df["department_unified"].nunique())
print(merged_df["department_unified"].isna().sum())

376
462

In [34]:
print(merged_df["department_unified"].value_counts().head(10))

department_unified
Labour Department                                          266
Agriculture, Farmers Welfare and Cooperation Department    222
Social Justice and Empowerment Department                  210
Agriculture Department                                     173
Social Welfare Department                                  130
Industries and Mines Department                            116
Labour and Employment Department                            84
Art, Culture and Museums Department                         80
Industries and Commerce Department, Puducherry              74
Department Of Higher Education                              71
Name: count, dtype: Int64

In [35]:
merged_df["department_unified"] = merged_df["department_unified"].replace(r"\s+", " ", regex=True).str.strip()
print(merged_df["department_unified"].nunique(), merged_df["department_unified"].isna().sum())

376 462

In [36]:
merged_df["category_unified"] = merged_df["category_hf"].astype("string").str.strip()
print("Missing category:", merged_df["category_unified"].isna().sum())
print("Unique categories:", merged_df["category_unified"].nunique())

Missing category: 173
Unique categories: 279

In [37]:
print(merged_df["category_unified"].value_counts().head(20))

category_unified
Education & Learning                                                     727
Social welfare & Empowerment                                             686
Agriculture,Rural & Environment                                          667
Business & Entrepreneurship                                              417
Social welfare & Empowerment, Women and Child                            155
Sports & Culture                                                         154
Skills & Employment                                                      127
Health & Wellness                                                        124
Education & Learning, Social welfare & Empowerment                        87
Banking,Financial Services and Insurance                                  72
Housing & Shelter                                                         65
Banking,Financial Services and Insurance, Business & Entrepreneurship     56
Education & Learning, Women and Child                                     50
Women and Child                                                           45
Science, IT & Communications                                              45
Social welfare & Empowerment, Education & Learning                        42
Agriculture,Rural & Environment, Business & Entrepreneurship              36
Business & Entrepreneurship, Skills & Employment                          35
Women and Child, Social welfare & Empowerment                             33
Health & Wellness, Social welfare & Empowerment                           33
Name: count, dtype: Int64

In [38]:
category_map = {"Agriculture,Rural & Environment": "Agriculture & Rural Development", "Social welfare & Empowerment": "Social Welfare & Empowerment", "Banking,Financial Services and Insurance": "Banking, Financial Services & Insurance"}
merged_df["category_unified"] = merged_df["category_unified"].replace(category_map)
print(merged_df["category_unified"].value_counts().head(20))

category_unified
Education & Learning                                                     727
Social Welfare & Empowerment                                             686
Agriculture & Rural Development                                          667
Business & Entrepreneurship                                              417
Social welfare & Empowerment, Women and Child                            155
Sports & Culture                                                         154
Skills & Employment                                                      127
Health & Wellness                                                        124
Education & Learning, Social welfare & Empowerment                        87
Banking, Financial Services & Insurance                                   72
Housing & Shelter                                                         65
Banking,Financial Services and Insurance, Business & Entrepreneurship     56
Education & Learning, Women and Child                                     50
Women and Child                                                           45
Science, IT & Communications                                              45
Social welfare & Empowerment, Education & Learning                        42
Agriculture,Rural & Environment, Business & Entrepreneurship              36
Business & Entrepreneurship, Skills & Employment                          35
Women and Child, Social welfare & Empowerment                             33
Health & Wellness, Social welfare & Empowerment                           33
Name: count, dtype: Int64

In [39]:
merged_df["category_unified"] = merged_df["category_unified"].str.replace("Social welfare & Empowerment", "Social Welfare & Empowerment", regex=False).str.replace("Agriculture,Rural & Environment", "Agriculture & Rural Development", regex=False).str.replace("Banking,Financial Services and Insurance", "Banking, Financial Services & Insurance", regex=False).str.replace(", ", ", ", regex=False)
print(merged_df["category_unified"].value_counts().head(20))

category_unified
Education & Learning                                                    727
Social Welfare & Empowerment                                            686
Agriculture & Rural Development                                         667
Business & Entrepreneurship                                             417
Social Welfare & Empowerment, Women and Child                           155
Sports & Culture                                                        154
Skills & Employment                                                     127
Health & Wellness                                                       124
Education & Learning, Social Welfare & Empowerment                       87
Banking, Financial Services & Insurance                                  72
Housing & Shelter                                                        65
Banking, Financial Services & Insurance, Business & Entrepreneurship     56
Education & Learning, Women and Child                                    50
Women and Child                                                          45
Science, IT & Communications                                             45
Social Welfare & Empowerment, Education & Learning                       42
Agriculture & Rural Development, Business & Entrepreneurship             36
Business & Entrepreneurship, Skills & Employment                         35
Women and Child, Social Welfare & Empowerment                            33
Health & Wellness, Social Welfare & Empowerment                          33
Name: count, dtype: Int64

In [40]:
merged_df["beneficiary_groups"] = merged_df["beneficiary_type_hf"].astype("string").str.strip()
print("Missing beneficiary groups:", merged_df["beneficiary_groups"].isna().sum())
print("Unique beneficiary values:", merged_df["beneficiary_groups"].nunique())

Missing beneficiary groups: 233
Unique beneficiary values: 197

In [41]:
print(merged_df["beneficiary_groups"].value_counts().head(20))

beneficiary_groups
Individual                                                                    3429
Business Entity                                                                231
Family                                                                         119
Business Entity, Industries                                                    118
Individual, Family                                                              90
Family, Individual                                                              51
Registered Societies                                                            36
University / Institution                                                        34
All                                                                             30
Industries                                                                      28
Artists                                                                         26
Individual, Self Help Groups (SHGS)                                             22
Business Entity, Individual                                                     20
Individual, Business Entity                                                     19
Individual, University / Institution                                            16
Self Help Groups (SHGS)                                                         13
Institution                                                                     12
NGO                                                                             11
Sportsperson                                                                    11
Individual, Business Entity, Registered Societies, Self Help Groups (SHGS)       9
Name: count, dtype: Int64

In [42]:
merged_df["application_mode_unified"] = merged_df["application_mode"].astype("string").str.strip()
print(merged_df["application_mode_unified"].value_counts(dropna=False))

application_mode_unified
<NA>                      2796
Online                     914
Offline                    868
Online & Offline           277
Direct / Not Specified       7
Name: count, dtype: Int64

In [43]:
merged_df["raw_tags_unified"] = merged_df["raw_tags"].astype("string").str.strip()
print("Missing tags:", merged_df["raw_tags_unified"].isna().sum())
print("Unique tag strings:", merged_df["raw_tags_unified"].nunique())

Missing tags: 2812
Unique tag strings: 2021

In [44]:
merged_df["description"] = merged_df["description_hf"].combine_first(merged_df["description_github"])
print("Missing description:", merged_df["description"].isna().sum())

Missing description: 3

In [45]:
merged_df["benefits_unified"] = merged_df["benefits_hf"].combine_first(merged_df["benefits"])
print("Missing benefits:", merged_df["benefits_unified"].isna().sum())

Missing benefits: 3

In [46]:
merged_df["eligibility_text"] = merged_df["eligibility_text_hf"].combine_first(merged_df["eligibility_criteria"]).combine_first(merged_df["eligibility_general"])
print("Missing eligibility text:", merged_df["eligibility_text"].isna().sum())

Missing eligibility text: 4

In [47]:
merged_df["exclusion_text_unified"] = merged_df["exclusion_text"].astype("string").str.strip()
print("Missing exclusion text:", merged_df["exclusion_text_unified"].isna().sum())

Missing exclusion text: 4483

In [48]:
merged_df["application_process_unified"] = merged_df["application_process_hf"].combine_first(merged_df["application_process"])
print("Missing application process:", merged_df["application_process_unified"].isna().sum())

Missing application process: 3

In [49]:
merged_df["documents_required_unified"] = merged_df["documents_required_hf"].combine_first(merged_df["documents_required"])
print("Missing documents:", merged_df["documents_required_unified"].isna().sum())

Missing documents: 17

In [50]:
merged_df["faqs_unified"] = merged_df["faqs"].astype("string").str.strip()
print("Missing FAQs:", merged_df["faqs_unified"].isna().sum())

Missing FAQs: 2796

In [51]:
merged_df["official_url"] = merged_df["official_url_hf"].combine_first(merged_df["official_url_github"])
merged_df["myscheme_url_unified"] = merged_df["myscheme_url"].astype("string").str.strip()
merged_df["apply_url_unified"] = merged_df["apply_url"].astype("string").str.strip()
print("Missing official URL:", merged_df["official_url"].isna().sum())
print("Missing MyScheme URL:", merged_df["myscheme_url_unified"].isna().sum())
print("Missing apply URL:", merged_df["apply_url_unified"].isna().sum())

Missing official URL: 0
Missing MyScheme URL: 2796
Missing apply URL: 178

In [52]:
merged_df["age_min_unified"] = merged_df["age_min"]
merged_df["age_max_unified"] = merged_df["age_max"]
merged_df["income_max_unified"] = merged_df["income_max"]
merged_df["gender_eligibility_unified"] = merged_df["gender_eligibility"].astype("string").str.strip()
merged_df["caste_category_unified"] = merged_df["caste_category"].astype("string").str.strip()
merged_df["residence_requirement_unified"] = merged_df["residence_requirement"].astype("string").str.strip()
merged_df["disability_eligibility_unified"] = merged_df["disability_eligibility"].astype("string").str.strip()
merged_df["bpl_required_unified"] = merged_df["bpl_required"].astype("string").str.strip()
print(merged_df[["age_min_unified","age_max_unified","income_max_unified","gender_eligibility_unified","caste_category_unified","residence_requirement_unified","disability_eligibility_unified","bpl_required_unified"]].isna().sum())

age_min_unified                   3809
age_max_unified                   4077
income_max_unified                4083
gender_eligibility_unified         169
caste_category_unified             169
residence_requirement_unified      169
disability_eligibility_unified     169
bpl_required_unified               169
dtype: int64

In [53]:
print(merged_df[["eligibility_text","age_min_unified","age_max_unified","income_max_unified"]].isna().sum())

eligibility_text         4
age_min_unified       3809
age_max_unified       4077
income_max_unified    4083
dtype: int64

In [54]:
merged_df["scraped_at_unified"] = merged_df["scraped_at"].astype("string").str.strip()
print("Missing scraped_at:", merged_df["scraped_at_unified"].isna().sum())

Missing scraped_at: 169

In [55]:
merged_df["source_hf"] = merged_df["_merge"].isin(["both", "left_only"])
merged_df["source_github"] = merged_df["_merge"].isin(["both", "right_only"])
merged_df["source_count"] = merged_df[["source_hf", "source_github"]].sum(axis=1)
print(merged_df[["source_hf", "source_github", "source_count"]].value_counts())

source_hf  source_github  source_count
True       False          1               2796
           True           2               1897
False      True           1                169
Name: count, dtype: int64

In [56]:
print(merged_df[["source_hf", "source_github", "source_count"]].sum())

source_hf        4693
source_github    2066
source_count     6759
dtype: int64

In [57]:
print(merged_df[["source_hf", "source_github", "source_count"]].value_counts())

source_hf  source_github  source_count
True       False          1               2796
           True           2               1897
False      True           1                169
Name: count, dtype: int64

In [58]:
print(merged_df[["source_hf", "source_github", "source_count"]].value_counts())

source_hf  source_github  source_count
True       False          1               2796
           True           2               1897
False      True           1                169
Name: count, dtype: int64

In [60]:
merged_df["source"] = np.select([merged_df["source_count"].eq(2), merged_df["source_hf"], merged_df["source_github"]], ["HF + GitHub", "HF", "GitHub"], default="Unknown")
print(merged_df["source"].value_counts())

source
HF             2796
HF + GitHub    1897
GitHub          169
Name: count, dtype: int64

In [61]:
print(merged_df[["scheme_id","scheme_name","source"]].head(10))

  scheme_id  \
0  108easuk
1   15dsugt
2      1pmy
3   25-ciss
4  40shydcs
5   6islbsa
6   6islbse
7  6isltvpb
8  a-gainer
9    a-pudu

                                                                                       scheme_name  \
0                                                   108, Emergency Ambulance Service - Uttarakhand
1                                                              15 Days Skill Up-gradation Training
2                                                                         100% Penalty Mafi Yojana
3                                                            25% Capital Investment Subsidy Scheme
4                                                40% Subsidy On Hank Yarn, Dyes & Chemicals Scheme
5                                6% Interest Subsidy on Loans taken through Banks for Study Abroad
6  6% Interest Subsidy on Loans taken through Banks up to a Limit of Rs.5 Lakh for Self-Employment
7                            6% Interest Subsidy on Loans taken for Vehicle Purchase through Banks
8                              AICTE - Grant For Augmenting Infrastructure In North Eastern Region
9                                                                                      ARAVANAIPPU

        source
0           HF
1           HF
2           HF
3  HF + GitHub
4  HF + GitHub
5           HF
6           HF
7           HF
8  HF + GitHub
9  HF + GitHub

In [62]:
merged_df["combined_text"] = merged_df[["scheme_name","description","benefits_unified","eligibility_text","exclusion_text_unified","application_process_unified","documents_required_unified","faqs_unified"]].fillna("").astype(str).apply(lambda x: "\n".join(f"{col}: {val}" for col, val in zip(["Scheme Name","Description","Benefits","Eligibility","Exclusions","Application Process","Documents Required","FAQs"], x) if val.strip()), axis=1)
print("Missing combined_text:", merged_df["combined_text"].eq("").sum())
print("Average combined_text length:", merged_df["combined_text"].str.len().mean())

Missing combined_text: 0
Average combined_text length: 4459.427807486631

In [63]:
print(merged_df[["scheme_id","scheme_name","combined_text"]].sample(5, random_state=42).to_string(index=False))

scheme_id                                                                                                                                                                                                                                          scheme_name                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               combined_text

In [64]:
print(merged_df[["scheme_id","scheme_name","combined_text"]].sample(5, random_state=42).to_string(index=False))

scheme_id                                                                                                                                                                                                                                          scheme_name                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               combined_text

In [65]:
import html
merged_df["combined_text"] = merged_df["combined_text"].apply(lambda x: html.unescape(str(x)).replace("\\n", "\n").replace("/n", "\n").replace("<br>", "\n").strip())
print("Average combined_text length:", merged_df["combined_text"].str.len().mean())
print("Empty combined_text:", merged_df["combined_text"].eq("").sum())

Average combined_text length: 4452.11065405183
Empty combined_text: 0

In [66]:
print(merged_df[["scheme_id","scheme_name","combined_text"]].sample(5, random_state=42).to_string(index=False))

scheme_id                                                                                                                                                                                                                                          scheme_name                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             combined_text

In [67]:
import re
merged_df["combined_text"] = merged_df["combined_text"].apply(lambda x: re.sub(r"\\([*_`])", r"\1", str(x)).replace("\\", "").replace("&#39;", "'").replace("&#x20;", " ").strip())

In [68]:
print(merged_df["combined_text"].str.len().describe())
print("Empty combined_text:", merged_df["combined_text"].eq("").sum())
print("Missing combined_text:", merged_df["combined_text"].isna().sum())

count     4862.000000
mean      4451.698478
std       2862.959763
min         42.000000
25%       2405.000000
50%       3776.500000
75%       5795.750000
max      32013.000000
Name: combined_text, dtype: float64
Empty combined_text: 0
Missing combined_text: 0

In [69]:
print(merged_df[["scheme_id","scheme_name","combined_text"]].sort_values("combined_text", key=lambda x: x.str.len()).head(10).to_string(index=False))

scheme_id                                                                       scheme_name                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      combined_text
     vpby                                                     Varishtha Pension Bima Yojana                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Scheme Name: Varishtha Pension Bima Yojana
fafmftcwd                     Financial assistance for Marriage for the Construction Worker                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Scheme Name: Financial assistance for Marriage for the Construction Worker
  visvasi Vanchit Ikai Samooh aur Vargon ki Aarthik Sahayata Yojana (VISVAS) for Individual                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Scheme Name: Vanchit Ikai Samooh aur Vargon ki Aarthik Sahayata Yojana (VISVAS) for Individual
      sdu                                                                        Seed Grant                                                                                                                                                                                                                                                                     Scheme Name: Seed Grant\nDescription: The scheme aims to provide seeds to farmers at a concessional rate during Kisan Melas with a subsidy of up to 15%.\nBenefits: Farmers are provided seeds at a subsidy of up to 15% during Kisan Melas.\n\n\nEligibility: 1. The applicant must be a farmer.\n\n\n\nApplication Process: [Offline]\nAll farmers are provided seeds during Kisan Melas on the basis of availability.\nDocuments Required: 1. Identity card\n2. Other documents as required
    aaiay                       Aawasiy Suvidha 1 – Indralok Aawasiy Yojana (Group Housing)                                                                                         Scheme Name: Aawasiy Suvidha 1 – Indralok Aawasiy Yojana (Group Housing)\nDescription: The scheme aims to provide residential facilities to homeless families through a registration process and lottery-based allotment.\nBenefits: Under this scheme, residential facilities are provided to homeless families.\n\n\nEligibility: 1. The applicant must be a resident of Uttarakhand.\n\n\n\nApplication Process: [Offline]\nThe Authority selects residential units through registration and allotment is done through lottery draw.\nDocuments Required: The required documents must be submitted as per the guidelines of the Haridwar-Roorkee Development Authority.
    kupuk                                              Kala Utsav Pratiyogita - Uttarakhand                                                                  Scheme Name: Kala Utsav Pratiyogita - Uttarakhand\nDescription: The scheme aims to promote and encourage artistic talent among school students of Classes 9 to 12.\nBenefits: A total of 20 students, who secured first place in 10 categories across boys’ and girls’ groups, participated in the National Level Kala Utsav Pratiyogita held at Bal Bhavan, New Delhi, representing the state.\n\n\nEligibility: 1. The applicant must be a student of Classes 9 to 12.\n1. The applicant must be studying in a school in Uttarakhand.\n\n\n\nApplication Process: [Offline]\nThe student (awardee) will be selected through competitions conducted at the district, state, and national levels.
     itfh                                                 Integrated Toll Free 104 Helpline                                    Scheme Name: Integrated Toll Free 104 Helpline\nDescription: The scheme aims to provide the general public with round-the-clock (24×7×365) access to reliable health information and medical advice through the toll-free number 104.\nBenefits: Under the National Health Mission (NHM), the Integrated Toll-Free 104 Helpline is being operated 24×7×365day. Through this helpline, health-related advice and information can be obtained.\n\n\nEligibility: 1. The general public of Uttarakhand is eligible to avail the benefits.\n\n\n\nApplication Process: [Offline]\nThe related information can be obtained by calling the helpline number 104.\nDocuments Required: No documents are required to avail the benefits.
   mksybs                                               Mukhyamantri Kishori Swasthya Yojna                           Scheme Name: Mukhyamantri Kishori Swasthya Yojna\nDescription: This initiative by the State Government aimed at reducing school dropout rates among adolescent girls by providing free sanitary napkins, promoting hygiene, and supporting their overall health.\nBenefits: - Free sanitary napkins for adolescent girls in secondary schools.\n\n\n\nEligibility: - The applicant must be a resident of Bihar.\n- The applicant must be a girl.\n- The applicant must be enrolled in a recognized secondary school.\nApplication Process: [Offline]\nContact the concerned school Administration to avail the scheme benefits.\nDocuments Required: Birth Certificate or School Admission Certificate.\nAny other document if required.
  ssiscpp         Special Scheme for Increasing the Storage Capacity of Perishable Products                 Scheme Name: Special Scheme for Increasing the Storage Capacity of Perishable Products\nDescription: The scheme aims to increase the storage capacity of perishable products by providing grant assistance for cold storage facilities.\nBenefits: - Grant Assistance: A grant of 50% of the project cost up to a maximum of ₹2,00,00,000/- for cold storage facilities up to 5,000 metric tons capacity.\n\n\n\nEligibility: - The applicant must be a farmer.\n  - The applicant must be a resident of Madhya Pradesh.\n\n\n\nApplication Process: [Offline]\nThe applicant should contact the District Office of the Horticulture Department.\nDocuments Required: Proof of Identity.\nResidence Certificate.\nAny other documents as required.
  whl-181                                                                    Women Helpline Scheme Name: Women Helpline\nDescription: "Women Helpline" provides 24X7 emergency and non-emergency response through the telephonic short-code 181 to women\nBenefits: - Emergency assistance.\n- Non-emergency assistance.\n- Information about government schemes and services.\n- Referral services.\n\n\n\nEligibility: - Any woman in distress seeking emergency\non- emergency services or information or any other individual on her behalf can connect with the Women Helpline by calling the toll free 181.\n\n\n\nApplication Process: [Offline]\nThe Women Helpline can be contacted through a single universal toll-free number across the country, which is 181\nDocuments Required: No documents are required to avail assistance under the scheme.

In [70]:
print(merged_df[["scheme_id","scheme_name","description","benefits_unified","eligibility_text","application_process_unified","documents_required_unified"]].isna().sum())

scheme_id                       0
scheme_name                     0
description                     3
benefits_unified                3
eligibility_text                4
application_process_unified     3
documents_required_unified     17
dtype: int64

In [71]:
print(merged_df.loc[merged_df[["description","benefits_unified","eligibility_text","application_process_unified","documents_required_unified"]].isna().any(axis=1), ["scheme_id","scheme_name","description","benefits_unified","eligibility_text","application_process_unified","documents_required_unified"]].to_string(index=False))

                                  scheme_id                                                                                                                                                                                             scheme_name                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  benefits_unified                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 eligibility_text                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               application_process_unified                 documents_required_unified

In [72]:
print(merged_df[["description","benefits_unified","eligibility_text","application_process_unified","documents_required_unified"]].isna().sum())

description                     3
benefits_unified                3
eligibility_text                4
application_process_unified     3
documents_required_unified     17
dtype: int64

In [73]:
print(merged_df.loc[merged_df[["description","benefits_unified","eligibility_text","application_process_unified","documents_required_unified"]].isna().any(axis=1), ["scheme_id","scheme_name","source"]].to_string(index=False))

                                  scheme_id                                                                                                                                                                                             scheme_name      source
                                        cia                                                                                                                                              Cash Incentive Award to Bonafede Meritorious Sportspersons          HF
                                       eesd                                                                                                                                                                  Endeavour To Empower-Skill Development          HF
                                  fafmftcwd                                                                                                                                           Financial assistance for Marriage for the Construction Worker          HF
                             journal-grants Scheme of Grant-in-Aid for Professional Associations/ Organisations of Social Scientists including Universities, Colleges and Research Institutes for Publication/ Running of their Research Journal(s)          HF
                                      kupuk                                                                                                                                                                    Kala Utsav Pratiyogita - Uttarakhand          HF
                                      mmbsy                                                                                                                                                                       Mukhya Mantri Bal Suposhan Yojana      GitHub
                                     mmekdp                                                                                                                                                                      Mukhya Mantrir Eti koli duti paat           HF
                                       mrin                                                                                                                                                                     Market Research Information Network      GitHub
                                     pmjjby                                                                                                                                                                 Pradhan Mantri Jeevan Jyoti Bima Yojana HF + GitHub
                                      pmsby                                                                                                                                                                     Pradhan Mantri Suraksha Bima Yojana HF + GitHub
                          publication-grant                                                                  Scheme of Publication Grant/Subsidy for Publication of Doctoral Thesis/Research Report/ Papers Presented in Seminars/Conferences, etc.          HF
                                       rkvy                                                                                                                                                                           Rashtriya Krishi Vikas Yojana      GitHub
                     scheme-of-grant-in-aid                Scheme of Grants-in-Aid for supporting professional associations/ organisations of social scientists, companies and trusts duly registered under the Companies Act for their development          HF
          supply-of-school-uniform-tie-belt                                                                                                                    Supply of School Uniform and Tie belt to SC/ST Boys/ Girls Students of Std I to VIII          HF
supply-of-stationery-socks-shoes-school-bag                                                                                                            Supply of School Stationery, Socks, Shoes, School Bag, etc. to all Students of Std I to VIII          HF
                                     svyfdb                                                                                                                                          Saraswati Vidya Yojana: Free Distribution of Bicycles - DNH&DD          HF
                                    visvasi                                                                                                                       Vanchit Ikai Samooh aur Vargon ki Aarthik Sahayata Yojana (VISVAS) for Individual          HF
                                       vpby                                                                                                                                                                           Varishtha Pension Bima Yojana          HF

In [74]:
missing_cols = ["description","benefits_unified","eligibility_text","application_process_unified","documents_required_unified"]
print(merged_df.loc[merged_df[missing_cols].isna().any(axis=1), ["scheme_id","scheme_name","source"] + missing_cols].to_string(index=False))

                                  scheme_id                                                                                                                                                                                             scheme_name      source                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  benefits_unified                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 eligibility_text                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               application_process_unified                 documents_required_unified

In [75]:
missing_cols = ["description","benefits_unified","eligibility_text","application_process_unified","documents_required_unified"]
print(merged_df.loc[merged_df[missing_cols].isna().any(axis=1), ["scheme_id","scheme_name","source"] + missing_cols].notna().sum())

scheme_id                      18
scheme_name                    18
source                         18
description                    15
benefits_unified               15
eligibility_text               14
application_process_unified    15
documents_required_unified      1
dtype: int64

In [76]:
print(merged_df.loc[merged_df[missing_cols].isna().any(axis=1), ["scheme_id","scheme_name"]].to_string(index=False))

                                  scheme_id                                                                                                                                                                                             scheme_name
                                        cia                                                                                                                                              Cash Incentive Award to Bonafede Meritorious Sportspersons
                                       eesd                                                                                                                                                                  Endeavour To Empower-Skill Development
                                  fafmftcwd                                                                                                                                           Financial assistance for Marriage for the Construction Worker
                             journal-grants Scheme of Grant-in-Aid for Professional Associations/ Organisations of Social Scientists including Universities, Colleges and Research Institutes for Publication/ Running of their Research Journal(s)
                                      kupuk                                                                                                                                                                    Kala Utsav Pratiyogita - Uttarakhand
                                      mmbsy                                                                                                                                                                       Mukhya Mantri Bal Suposhan Yojana
                                     mmekdp                                                                                                                                                                      Mukhya Mantrir Eti koli duti paat
                                       mrin                                                                                                                                                                     Market Research Information Network
                                     pmjjby                                                                                                                                                                 Pradhan Mantri Jeevan Jyoti Bima Yojana
                                      pmsby                                                                                                                                                                     Pradhan Mantri Suraksha Bima Yojana
                          publication-grant                                                                  Scheme of Publication Grant/Subsidy for Publication of Doctoral Thesis/Research Report/ Papers Presented in Seminars/Conferences, etc.
                                       rkvy                                                                                                                                                                           Rashtriya Krishi Vikas Yojana
                     scheme-of-grant-in-aid                Scheme of Grants-in-Aid for supporting professional associations/ organisations of social scientists, companies and trusts duly registered under the Companies Act for their development
          supply-of-school-uniform-tie-belt                                                                                                                    Supply of School Uniform and Tie belt to SC/ST Boys/ Girls Students of Std I to VIII
supply-of-stationery-socks-shoes-school-bag                                                                                                            Supply of School Stationery, Socks, Shoes, School Bag, etc. to all Students of Std I to VIII
                                     svyfdb                                                                                                                                          Saraswati Vidya Yojana: Free Distribution of Bicycles - DNH&DD
                                    visvasi                                                                                                                       Vanchit Ikai Samooh aur Vargon ki Aarthik Sahayata Yojana (VISVAS) for Individual
                                       vpby                                                                                                                                                                           Varishtha Pension Bima Yojana

In [77]:
print(merged_df.loc[merged_df["description"].isna() | merged_df["benefits_unified"].isna() | merged_df["eligibility_text"].isna() | merged_df["application_process_unified"].isna(), ["scheme_id","scheme_name","source"]].to_string(index=False))

scheme_id                                                                       scheme_name source
fafmftcwd                     Financial assistance for Marriage for the Construction Worker     HF
     mrin                                               Market Research Information Network GitHub
  visvasi Vanchit Ikai Samooh aur Vargon ki Aarthik Sahayata Yojana (VISVAS) for Individual     HF
     vpby                                                     Varishtha Pension Bima Yojana     HF

In [78]:
cols = ["scheme_id","scheme_name","description_hf","description_github","benefits_hf","benefits","eligibility_text_hf","eligibility_criteria","eligibility_general","application_process_hf","application_process"]
print(merged_df.loc[merged_df["scheme_id"].isin(["fafmftcwd","mrin","visvasi","vpby"]), cols].T.to_string())

                                                                                 1229                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      2714                                                                               4708                           4718
scheme_id                                                                   fafmftcwd                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      mrin                                                                            visvasi                           vpby
scheme_name             Financial assistance for Marriage for the Construction Worker                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Market Research Information Network  Vanchit Ikai Samooh aur Vargon ki Aarthik Sahayata Yojana (VISVAS) for Individual  Varishtha Pension Bima Yojana
description_hf                                                                    NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       NaN                                                                                NaN                            NaN

In [79]:
text_cols = ["description","benefits_unified","eligibility_text","exclusion_text_unified","application_process_unified","documents_required_unified","faqs_unified"]
merged_df[text_cols] = merged_df[text_cols].fillna("")

In [80]:
text_map = {"Scheme Name":"scheme_name","Government Level":"government_level_unified","State/UT":"state_ut","Ministry":"ministry","Department":"department_unified","Category":"category_unified","Beneficiary":"beneficiary_groups","Application Mode":"application_mode_unified","Description":"description","Benefits":"benefits_unified","Eligibility":"eligibility_text","Exclusions":"exclusion_text_unified","Application Process":"application_process_unified","Documents Required":"documents_required_unified","FAQs":"faqs_unified"}
merged_df["combined_text"] = merged_df[list(text_map.values())].fillna("").astype(str).apply(lambda x: "\n".join(f"{k}: {v}" for k,v in zip(text_map.keys(),x) if v.strip() and v.strip().lower() != "nan"), axis=1)
print(merged_df["combined_text"].str.len().describe())

count     4862.000000
mean      4636.082065
std       2870.653174
min         68.000000
25%       2573.000000
50%       3959.500000
75%       5984.750000
max      32277.000000
Name: combined_text, dtype: float64

In [82]:
print(merged_df.loc[merged_df["combined_text"].str.len().sort_values().head(15).index, ["scheme_id","scheme_name","source","combined_text"]].to_string(index=False))

scheme_id                                                                       scheme_name source                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   combined_text
     vpby                                                     Varishtha Pension Bima Yojana     HF                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Scheme Name: Varishtha Pension Bima Yojana\nGovernment Level: Central
  visvasi Vanchit Ikai Samooh aur Vargon ki Aarthik Sahayata Yojana (VISVAS) for Individual     HF                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Scheme Name: Vanchit Ikai Samooh aur Vargon ki Aarthik Sahayata Yojana (VISVAS) for Individual\nGovernment Level: Central
fafmftcwd                     Financial assistance for Marriage for the Construction Worker     HF                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Scheme Name: Financial assistance for Marriage for the Construction Worker\nGovernment Level: State/UT\nState/UT: Dadra & Nagar Haveli and Daman & Diu
      sdu                                                                        Seed Grant     HF                                                                                                                                                                                                                                                                                                                                   Scheme Name: Seed Grant\nGovernment Level: State/UT\nState/UT: Uttarakhand\nDepartment: Agriculture Department\nCategory: Agriculture & Rural Development\nBeneficiary: Individual\nDescription: The scheme aims to provide seeds to farmers at a concessional rate during Kisan Melas with a subsidy of up to 15%.\nBenefits: Farmers are provided seeds at a subsidy of up to 15% during Kisan Melas.\n<br>\nEligibility: 1. The applicant must be a farmer.\n\n<br>\nApplication Process: [Offline]\nAll farmers are provided seeds during Kisan Melas on the basis of availability.\nDocuments Required: 1. Identity card\n2. Other documents as required
    aaiay                       Aawasiy Suvidha 1 – Indralok Aawasiy Yojana (Group Housing)     HF                                                                                                                                                                         Scheme Name: Aawasiy Suvidha 1 – Indralok Aawasiy Yojana (Group Housing)\nGovernment Level: State/UT\nState/UT: Uttarakhand\nDepartment: Housing Department\nCategory: Housing & Shelter\nBeneficiary: Individual\nDescription: The scheme aims to provide residential facilities to homeless families through a registration process and lottery-based allotment.\nBenefits: Under this scheme, residential facilities are provided to homeless families.\n<br>\nEligibility: 1. The applicant must be a resident of Uttarakhand.\n\n<br>\nApplication Process: [Offline]\nThe Authority selects residential units through registration and allotment is done through lottery draw.\nDocuments Required: The required documents must be submitted as per the guidelines of the Haridwar-Roorkee Development Authority.
    kupuk                                              Kala Utsav Pratiyogita - Uttarakhand     HF                                                                                                                                              Scheme Name: Kala Utsav Pratiyogita - Uttarakhand\nGovernment Level: State/UT\nState/UT: Uttarakhand\nDepartment: Department Of Education\nCategory: Sports & Culture\nBeneficiary: Individual\nDescription: The scheme aims to promote and encourage artistic talent among school students of Classes 9 to 12.\nBenefits: A total of 20 students, who secured first place in 10 categories across boys’ and girls’ groups, participated in the National Level Kala Utsav Pratiyogita held at Bal Bhavan, New Delhi, representing the state.\n<br>\nEligibility: 1. The applicant must be a student of Classes 9 to 12.\n1. The applicant must be studying in a school in Uttarakhand.\n\n<br>\nApplication Process: [Offline]\nThe student (awardee) will be selected through competitions conducted at the district, state, and national levels.
  whl-181                                                                    Women Helpline     HF                                                                                                                 Scheme Name: Women Helpline\nGovernment Level: Central\nMinistry: Ministry of Women and Child Development\nCategory: Women and Child\nDescription: "Women Helpline" provides 24X7 emergency and non-emergency response through the telephonic short-code 181 to women\nBenefits: - Emergency assistance.\n- Non-emergency assistance.\n- Information about government schemes and services.\n- Referral services.\n\n<br>\nEligibility: - Any woman in distress seeking emergency/non- emergency services or information or any other individual on her behalf can connect with the Women Helpline by calling the toll free 181.\n\n<br>\nApplication Process: [Offline]\nThe Women Helpline can be contacted through a single universal toll-free number across the country, which is 181\nDocuments Required: No documents are required to avail assistance under the scheme.
   mksybs                                               Mukhyamantri Kishori Swasthya Yojna     HF                                                                                                           Scheme Name: Mukhyamantri Kishori Swasthya Yojna\nGovernment Level: State/UT\nState/UT: Bihar\nDepartment: Education Department\nCategory: Health & Wellness\nBeneficiary: Individual\nDescription: This initiative by the State Government aimed at reducing school dropout rates among adolescent girls by providing free sanitary napkins, promoting hygiene, and supporting their overall health.\nBenefits: - Free sanitary napkins for adolescent girls in secondary schools.\n\n&lt;br&gt;\nEligibility: - The applicant must be a resident of Bihar.\n- The applicant must be a girl.\n- The applicant must be enrolled in a recognized secondary school.\nApplication Process: [Offline]\nContact the concerned school Administration to avail the scheme benefits.\nDocuments Required: Birth Certificate or School Admission Certificate.\nAny other document if required.
     itfh                                                 Integrated Toll Free 104 Helpline     HF                                                                                          Scheme Name: Integrated Toll Free 104 Helpline\nGovernment Level: State/UT\nState/UT: Uttarakhand\nDepartment: Medical Health And Family Welfare Department\nCategory: Health & Wellness\nBeneficiary: Individual\nDescription: The scheme aims to provide the general public with round-the-clock (24×7×365) access to reliable health information and medical advice through the toll-free number 104.\nBenefits: Under the National Health Mission (NHM), the Integrated Toll-Free 104 Helpline is being operated 24×7×365day. Through this helpline, health-related advice and information can be obtained.\n<br>\nEligibility: 1. The general public of Uttarakhand is eligible to avail the benefits.\n\n<br>\nApplication Process: [Offline]\nThe related information can be obtained by calling the helpline number 104.\nDocuments Required: No documents are required to avail the benefits.
  mmbpybb                                                 Mukhya Mantri Balika Poshak Yojna     HF                                                                               Scheme Name: Mukhya Mantri Balika Poshak Yojna\nGovernment Level: State/UT\nState/UT: Bihar\nDepartment: Education Department\nCategory: Education & Learning\nBeneficiary: Individual\nDescription: The "Mukhya Mantri Balika Poshak Yojna" is a government initiative launched to encourage the enrollment and retention of girl students in schools by providing them with school uniforms.\nBenefits: - A pair of school uniforms to girls in Classes VI to VII.\nEligibility: - The applicant must be a resident of Bihar.\n  - The applicant must be a girl student.\n  - She should be enrolled in Classes VI or VII.\n  - Enrollment must be in a government school within the state.\nApplication Process: [Offline]\nContact the concerned school Administration to avail the scheme benefits.\nDocuments Required: Birth Certificate or School Admission Certificate.\nAny other document if required.
  ssiscpp         Special Scheme for Increasing the Storage Capacity of Perishable Products     HF                                                       Scheme Name: Special Scheme for Increasing the Storage Capacity of Perishable Products\nGovernment Level: State/UT\nState/UT: Madhya Pradesh\nDepartment: Horticulture and Food Processing Department\nCategory: Agriculture & Rural Development\nBeneficiary: Individual\nDescription: The scheme aims to increase the storage capacity of perishable products by providing grant assistance for cold storage facilities.\nBenefits: - Grant Assistance: A grant of 50% of the project cost up to a maximum of ₹2,00,00,000/- for cold storage facilities up to 5,000 metric tons capacity.\n\n<br>\nEligibility: - The applicant must be a farmer.\n  - The applicant must be a resident of Madhya Pradesh.\n\n<br>\nApplication Process: [Offline]\nThe applicant should contact the District Office of the Horticulture Department.\nDocuments Required: Proof of Identity.\nResidence Certificate.\nAny other documents as required.
     kspc                                    Kishor Swasthya Paramarsh Clinic - Uttarakhand     HF                                                    Scheme Name: Kishor Swasthya Paramarsh Clinic - Uttarakhand\nGovernment Level: State/UT\nState/UT: Uttarakhand\nDepartment: Medical Health And Family Welfare Department\nCategory: Health & Wellness\nBeneficiary: Individual\nDescription: This initiative aims to promote the physical, mental, and emotional well-being of adolescents aged 10 to 19 years by providing free health counselling and guidance.\nBenefits: Free counselling services are provided at the Adolescent Health Clinics.\n<br>\nEligibility: 1. The beneficiary must be an adolescent between 10 and 19 years of age from Uttarakhand.\n\n<br>\nApplication Process: [Offline]\nFree consultation is provided upon registration at 13 district hospitals, 2 sub-district hospitals, and 45 community health centres across the state.\nDocuments Required: Documents are required as per the guidelines prescribed for the dedicated Adolescent Health Clinics.
    pmmrc                                 Providing Model Maps for Residential Construction     HF                                  Scheme Name: Providing Model Maps for Residential Construction\nGovernment Level: State/UT\nState/UT: Uttarakhand\nDepartment: Housing Department\nCategory: Housing & Shelter\nBeneficiary: Individual\nDescription: It aims to provide landowners in Haridwar district with model maps for residential construction according to the size of their plots.\nBenefits: Model maps for residential construction are provided to all landowners across Haridwar district.\n<br>\nEligibility: 1. All landowners in the Haridwar district of Uttarakhand are eligible.\n\n<br>\nApplication Process: [Online]\nFor the convenience of landowners in Haridwar district, model maps have been uploaded on the authority’s website. Landowners can select a model map according to the area of their plot and avail the facility.\nDocuments Required: The required documents must be submitted as per the guidelines of the Haridwar-Roorkee Development Authority.
 rlbarpyu                                              Rani Laxmi Bai Self-Defense Training     HF Scheme Name: Rani Laxmi Bai Self-Defense Training\nGovernment Level: State/UT\nState/UT: Uttarakhand\nDepartment: Department Of Education\nCategory: Education & Learning, Women and Child\nBeneficiary: Individual\nDescription: The scheme aims to provide free self-defense skills training (including judo, karate, martial arts, and boxing) to girl students in upper primary and secondary schools across Uttarakhand.\nBenefits: Free self-defense techniques training is provided to girl students.\n<br>\nEligibility: 1. The applicant (girl student) must be studying in an upper primary or secondary government school in Uttarakhand.\n\n<br>\nApplication Process: [Offline]\nSelf-defense skills training (judo, karate, martial arts, and boxing) is provided to female students in upper primary and secondary schools across the state. All girls in each selected school are included in the training.\nDocuments Required: Documents as required by the concerned school.
      mlc                                                 Mobile Learning Centre (UKBOCWWB)     HF Scheme Name: Mobile Learning Centre (UKBOCWWB)\nGovernment Level: State/UT\nState/UT: Uttarakhand\nDepartment: Department Of Labour\nCategory: Education & Learning\nBeneficiary: Individual\nDescription: The scheme aims to provide education to the children of registered construction workers at construction sites through Mobile Learning Centre buses, ensuring their better and brighter future.\nBenefits: Under this scheme, mobile learning schools are operated to provide education to the children of construction workers.\n<br>\nEligibility: Children of workers registered with the Uttarakhand Building and Other Construction Workers Welfare Board are eligible to avail the benefits of this scheme.\n<br>\nApplication Process: [Offline]\nFor securing a bright future for the children of construction site workers, education is provided at construction sites through Mobile Learning Centre buses.\nDocuments Required: 1. Labour card of the construction worker

In [83]:
print("Duplicate combined_text:", merged_df["combined_text"].duplicated().sum())

Duplicate combined_text: 0

In [84]:
print("Rows:", len(merged_df))
print("Unique scheme_id:", merged_df["scheme_id"].nunique())
print("Duplicate scheme_id:", merged_df["scheme_id"].duplicated().sum())
print("Missing scheme_id:", merged_df["scheme_id"].isna().sum())
print("Unique scheme_name:", merged_df["scheme_name"].nunique())
print("Duplicate scheme_name:", merged_df["scheme_name"].duplicated().sum())
print("Missing scheme_name:", merged_df["scheme_name"].isna().sum())

Rows: 4862
Unique scheme_id: 4862
Duplicate scheme_id: 0
Missing scheme_id: 0
Unique scheme_name: 4862
Duplicate scheme_name: 0
Missing scheme_name: 0

In [85]:
print(merged_df[["source_hf","source_github","source_count","source"]].value_counts(dropna=False).sort_index())
print("\nSource count totals:", merged_df["source_count"].sum())
print("Invalid source_count:", (~merged_df["source_count"].isin([1,2])).sum())

source_hf  source_github  source_count  source
False      True           1             GitHub          169
True       False          1             HF             2796
           True           2             HF + GitHub    1897
Name: count, dtype: int64

Source count totals: 6759
Invalid source_count: 0

In [86]:
final_candidate_cols = ["scheme_id","scheme_name","scheme_slug","government_level_unified","state_ut","ministry","department_unified","category_unified","raw_tags_unified","beneficiary_groups","age_min_unified","age_max_unified","income_max_unified","gender_eligibility_unified","caste_category_unified","residence_requirement_unified","disability_eligibility_unified","bpl_required_unified","eligibility_text","exclusion_text_unified","description","benefits_unified","application_mode_unified","application_process_unified","documents_required_unified","faqs_unified","official_url","myscheme_url_unified","apply_url_unified","source_hf","source_github","source_count","source","scraped_at_unified","combined_text"]
print(merged_df[final_candidate_cols].isna().sum().sort_values(ascending=False).to_string())

ministry                          4098
income_max_unified                4083
age_max_unified                   4077
age_min_unified                   3809
raw_tags_unified                  2812
myscheme_url_unified              2796
application_mode_unified          2796
state_ut                           764
department_unified                 462
beneficiary_groups                 233
apply_url_unified                  178
category_unified                   173
disability_eligibility_unified     169
gender_eligibility_unified         169
scraped_at_unified                 169
bpl_required_unified               169
residence_requirement_unified      169
caste_category_unified             169
scheme_id                            0
scheme_slug                          0
scheme_name                          0
eligibility_text                     0
government_level_unified             0
application_process_unified          0
exclusion_text_unified               0
description                          0
benefits_unified                     0
official_url                         0
faqs_unified                         0
documents_required_unified           0
source_hf                            0
source_github                        0
source_count                         0
source                               0
combined_text                        0

In [87]:
print("Government level:")
print(merged_df["government_level_unified"].value_counts(dropna=False).to_string())
print("\nState/UT samples:")
print(merged_df["state_ut"].dropna().value_counts().head(30).to_string())

Government level:
government_level_unified
State/UT    4098
Central      764

State/UT samples:
state_ut
Gujarat                                 639
Uttarakhand                             448
Madhya Pradesh                          286
Goa                                     272
Puducherry                              270
Haryana                                 246
Tamil Nadu                              232
Rajasthan                               158
Bihar                                   113
West Bengal                             112
Chhattisgarh                            107
Jharkhand                                95
Odisha                                   89
Maharashtra                              85
Meghalaya                                84
Assam                                    82
Kerala                                   81
Himachal Pradesh                         71
Andhra Pradesh                           65
Karnataka                                64
Dadra & Nagar Haveli and Daman & Diu     61
Delhi                                    53
Jammu and Kashmir                        44
Uttar Pradesh                            44
Punjab                                   41
Tripura                                  40
Arunachal Pradesh                        39
Mizoram                                  28
Manipur                                  27
Telangana                                25

In [88]:
print(merged_df.loc[merged_df["state_ut"].notna() & merged_df["state_ut"].str.contains("Dadra|Daman|Nagar", case=False, regex=True), "state_ut"].value_counts().to_string())

state_ut
Dadra & Nagar Haveli and Daman & Diu        61
Andaman and Nicobar Islands                 19
Dadra and Nagar Haveli and Daman and Diu     1

In [89]:
merged_df["state_ut"] = merged_df["state_ut"].replace({"Dadra and Nagar Haveli and Daman and Diu": "Dadra & Nagar Haveli and Daman & Diu"})
print(merged_df["state_ut"].dropna().value_counts().loc[lambda x: x.index.str.contains("Dadra|Daman|Nagar", case=False, regex=True)].to_string())

state_ut
Dadra & Nagar Haveli and Daman & Diu    62
Andaman and Nicobar Islands             19

In [90]:
print(merged_df["category_unified"].dropna().value_counts().to_string())

category_unified
Education & Learning                                                                                                                                                            727
Social Welfare & Empowerment                                                                                                                                                    686
Agriculture & Rural Development                                                                                                                                                 667
Business & Entrepreneurship                                                                                                                                                     417
Social Welfare & Empowerment, Women and Child                                                                                                                                   155
Sports & Culture                                                                                                                                                                154
Skills & Employment                                                                                                                                                             127
Health & Wellness                                                                                                                                                               124
Education & Learning, Social Welfare & Empowerment                                                                                                                               87
Banking, Financial Services & Insurance                                                                                                                                          72
Housing & Shelter                                                                                                                                                                65
Banking, Financial Services & Insurance, Business & Entrepreneurship                                                                                                             56
Education & Learning, Women and Child                                                                                                                                            50
Women and Child                                                                                                                                                                  45
Science, IT & Communications                                                                                                                                                     45
Social Welfare & Empowerment, Education & Learning                                                                                                                               42
Agriculture & Rural Development, Business & Entrepreneurship                                                                                                                     36
Business & Entrepreneurship, Skills & Employment                                                                                                                                 35
Women and Child, Social Welfare & Empowerment                                                                                                                                    33
Health & Wellness, Social Welfare & Empowerment                                                                                                                                  33
Travel & Tourism                                                                                                                                                                 30
Sports & Culture, Social Welfare & Empowerment                                                                                                                                   30
Agriculture & Rural Development, Banking, Financial Services & Insurance                                                                                                         29
Health & Wellness, Women and Child                                                                                                                                               28
Education & Learning, Skills & Employment                                                                                                                                        26
Social Welfare & Empowerment, Skills & Employment                                                                                                                                24
Travel & Tourism, Business & Entrepreneurship                                                                                                                                    22
Social Welfare & Empowerment, Health & Wellness                                                                                                                                  22
Banking, Financial Services & Insurance, Social Welfare & Empowerment                                                                                                            20
Transport & Infrastructure                                                                                                                                                       19
Utility & Sanitation                                                                                                                                                             19
Housing & Shelter, Social Welfare & Empowerment                                                                                                                                  18
Skills & Employment, Social Welfare & Empowerment                                                                                                                                17
Education & Learning, Science, IT & Communications                                                                                                                               17
Women and Child, Health & Wellness                                                                                                                                               17
Social Welfare & Empowerment, Banking, Financial Services & Insurance                                                                                                            16
Agriculture & Rural Development, Social Welfare & Empowerment                                                                                                                    16
Agriculture & Rural Development, Skills & Employment                                                                                                                             15
Business & Entrepreneurship, Banking, Financial Services & Insurance                                                                                                             15
Skills & Employment, Business & Entrepreneurship                                                                                                                                 15
Skills & Employment, Sports & Culture                                                                                                                                            14
Business & Entrepreneurship, Women and Child                                                                                                                                     14
Education & Learning, Sports & Culture                                                                                                                                           13
Social Welfare & Empowerment, Transport & Infrastructure                                                                                                                         12
Social Welfare & Empowerment, Business & Entrepreneurship                                                                                                                        11
Science, IT & Communications, Education & Learning                                                                                                                               11
Business & Entrepreneurship, Social Welfare & Empowerment                                                                                                                        11
Education & Learning, Banking, Financial Services & Insurance                                                                                                                    10
Business & Entrepreneurship, Agriculture & Rural Development                                                                                                                     10
Banking, Financial Services & Insurance, Education & Learning                                                                                                                    10
Social Welfare & Empowerment, Sports & Culture                                                                                                                                   10
Agriculture & Rural Development, Transport & Infrastructure                                                                                                                       9
Public Safety,Law & Justice                                                                                                                                                       9
Travel & Tourism, Skills & Employment                                                                                                                                             9
Sports & Culture, Skills & Employment                                                                                                                                             9
Science, IT & Communications, Business & Entrepreneurship                                                                                                                         8
Business & Entrepreneurship, Science, IT & Communications                                                                                                                         8
Education & Learning, Social Welfare & Empowerment, Women and Child                                                                                                               8
Business & Entrepreneurship, Transport & Infrastructure                                                                                                                           8
Social Welfare & Empowerment, Housing & Shelter                                                                                                                                   7
Banking, Financial Services & Insurance, Women and Child                                                                                                                          7
Banking, Financial Services & Insurance, Agriculture & Rural Development                                                                                                          7
Sports & Culture, Social Welfare & Empowerment, Skills & Employment                                                                                                               6
Travel & Tourism, Social Welfare & Empowerment                                                                                                                                    6
Education & Learning, Housing & Shelter                                                                                                                                           6
Science, IT & Communications, Women and Child                                                                                                                                     6
Business & Entrepreneurship, Utility & Sanitation                                                                                                                                 5
Education & Learning, Agriculture & Rural Development                                                                                                                             5
Utility & Sanitation, Agriculture & Rural Development                                                                                                                             5
Banking, Financial Services & Insurance, Business & Entrepreneurship, Skills & Employment                                                                                         5
Transport & Infrastructure, Social Welfare & Empowerment                                                                                                                          4
Women and Child, Education & Learning                                                                                                                                             4
Education & Learning, Business & Entrepreneurship                                                                                                                                 4
Social Welfare & Empowerment, Public Safety,Law & Justice                                                                                                                         4
Agriculture & Rural Development, Health & Wellness                                                                                                                                4
Transport & Infrastructure, Agriculture & Rural Development                                                                                                                       4
Business & Entrepreneurship, Banking, Financial Services & Insurance, Social Welfare & Empowerment                                                                                4
Skills & Employment, Banking, Financial Services & Insurance                                                                                                                      4
Skills & Employment, Education & Learning                                                                                                                                         4
Education & Learning, Social Welfare & Empowerment, Skills & Employment                                                                                                           4
Banking, Financial Services & Insurance, Business & Entrepreneurship, Women and Child                                                                                             4
Education & Learning, Banking, Financial Services & Insurance, Social Welfare & Empowerment                                                                                       4
Banking, Financial Services & Insurance, Skills & Employment                                                                                                                      4
Women and Child, Business & Entrepreneurship                                                                                                                                      4
Travel & Tourism, Transport & Infrastructure                                                                                                                                      4
Public Safety,Law & Justice, Social Welfare & Empowerment                                                                                                                         4
Agriculture & Rural Development, Business & Entrepreneurship, Social Welfare & Empowerment                                                                                        4
Agriculture & Rural Development, Women and Child                                                                                                                                  4
Health & Wellness, Social Welfare & Empowerment, Women and Child                                                                                                                  4
Social Welfare & Empowerment, Travel & Tourism                                                                                                                                    3
Women and Child, Banking, Financial Services & Insurance                                                                                                                          3
Social Welfare & Empowerment, Women and Child, Education & Learning                                                                                                               3
Travel & Tourism, Education & Learning                                                                                                                                            3
Women and Child, Social Welfare & Empowerment, Housing & Shelter                                                                                                                  3
Public Safety,Law & Justice, Skills & Employment                                                                                                                                  3
Transport & Infrastructure, Travel & Tourism                                                                                                                                      3
Transport & Infrastructure, Business & Entrepreneurship                                                                                                                           3
Housing & Shelter, Women and Child                                                                                                                                                3
Women and Child, Social Welfare & Empowerment, Health & Wellness                                                                                                                  3
Agriculture & Rural Development, Utility & Sanitation                                                                                                                             3
Business & Entrepreneurship, Education & Learning                                                                                                                                 3
Women and Child, Skills & Employment                                                                                                                                              3
Skills & Employment, Health & Wellness                                                                                                                                            3
Skills & Employment, Sports & Culture, Social Welfare & Empowerment                                                                                                               3
Utility & Sanitation, Social Welfare & Empowerment                                                                                                                                3
Agriculture & Rural Development, Education & Learning                                                                                                                             3
Business & Entrepreneurship, Skills & Employment, Social Welfare & Empowerment                                                                                                    3
Social Welfare & Empowerment, Agriculture & Rural Development                                                                                                                     3
Skills & Employment, Social Welfare & Empowerment, Women and Child                                                                                                                3
Banking, Financial Services & Insurance, Social Welfare & Empowerment, Women and Child                                                                                            3
Skills & Employment, Social Welfare & Empowerment, Business & Entrepreneurship                                                                                                    2

In [91]:
print(merged_df["beneficiary_groups"].dropna().value_counts().head(50).to_string())

beneficiary_groups
Individual                                                                                                                                        3429
Business Entity                                                                                                                                    231
Family                                                                                                                                             119
Business Entity, Industries                                                                                                                        118
Individual, Family                                                                                                                                  90
Family, Individual                                                                                                                                  51
Registered Societies                                                                                                                                36
University / Institution                                                                                                                            34
All                                                                                                                                                 30
Industries                                                                                                                                          28
Artists                                                                                                                                             26
Individual, Self Help Groups (SHGS)                                                                                                                 22
Business Entity, Individual                                                                                                                         20
Individual, Business Entity                                                                                                                         19
Individual, University / Institution                                                                                                                16
Self Help Groups (SHGS)                                                                                                                             13
Institution                                                                                                                                         12
NGO                                                                                                                                                 11
Sportsperson                                                                                                                                        11
Individual, Business Entity, Registered Societies, Self Help Groups (SHGS)                                                                           9
Government Organisation                                                                                                                              9
Village                                                                                                                                              8
Business Entity, Individual, Registered Societies, Self Help Groups (SHGS)                                                                           7
Journalist                                                                                                                                           7
Individual, Business Entity, Industries                                                                                                              7
Industries, Business Entity                                                                                                                          7
Individual, Registered Societies, Self Help Groups (SHGS)                                                                                            6
Artists, Individual                                                                                                                                  6
University / Institution, Individual                                                                                                                 6
Individual, Self Help Groups (SHGS), Registered Societies                                                                                            5
State Government                                                                                                                                     5
Business Entity, Individual, Self Help Groups (SHGS), Registered Societies                                                                           5
Individual, Self Help Groups (SHGS), Business Entity                                                                                                 4
Sportsperson, Individual                                                                                                                             4
Individual, Industries                                                                                                                               4
Registered Societies, Individual                                                                                                                     4
Individual, Institution                                                                                                                              4
Individual, Business Entity, Self Help Groups (SHGS), Registered Societies                                                                           4
Individual, Joint Liability Groups (JLGS), Self Help Groups (SHGS)                                                                                   4
Business Entity, University / Institution                                                                                                            4
Government Organisation, Institution, NGO, Registered Societies, Trust                                                                               3
University / Institution, Business Entity                                                                                                            3
Individual, Registered Societies                                                                                                                     3
Individual, NGO                                                                                                                                      3
Registered Societies, Government Organisation                                                                                                        3
Individual, Artists                                                                                                                                  3
Individual, Joint Liability Groups (JLGS), Self Help Groups (SHGS), Registered Societies                                                             3
Individual, Village                                                                                                                                  3
Business Entity, Government Organisation, Industries, Joint Liability Groups (JLGS), NGO, Registered Societies, Self Help Groups (SHGS), Trust       3
Government Organisation, State Government                                                                                                            3

In [92]:
b = merged_df["beneficiary_groups"].dropna().str.split(", ").apply(lambda x: tuple(sorted(x)))
print(b.value_counts().head(30).to_string())

beneficiary_groups
(Individual,)                                                                                                                                       3429
(Business Entity,)                                                                                                                                   231
(Family, Individual)                                                                                                                                 141
(Business Entity, Industries)                                                                                                                        125
(Family,)                                                                                                                                            119
(Business Entity, Individual)                                                                                                                         39
(Registered Societies,)                                                                                                                               36
(University / Institution,)                                                                                                                           34
(All,)                                                                                                                                                30
(Industries,)                                                                                                                                         28
(Artists,)                                                                                                                                            26
(Business Entity, Individual, Registered Societies, Self Help Groups (SHGS))                                                                          26
(Individual, Self Help Groups (SHGS))                                                                                                                 24
(Individual, University / Institution)                                                                                                                22
(Individual, Registered Societies, Self Help Groups (SHGS))                                                                                           13
(Self Help Groups (SHGS),)                                                                                                                            13
(Institution,)                                                                                                                                        12
(NGO,)                                                                                                                                                11
(Business Entity, Individual, Industries)                                                                                                             11
(Sportsperson,)                                                                                                                                       11
(Artists, Individual)                                                                                                                                  9
(Government Organisation,)                                                                                                                             9
(Village,)                                                                                                                                             8
(Business Entity, Government Organisation, Industries, Joint Liability Groups (JLGS), NGO, Registered Societies, Self Help Groups (SHGS), Trust)       8
(Business Entity, University / Institution)                                                                                                            7
(Individual, Registered Societies)                                                                                                                     7
(Journalist,)                                                                                                                                          7
(Individual, Sportsperson)                                                                                                                             6
(Business Entity, Individual, Self Help Groups (SHGS))                                                                                                 6
(Individual, Joint Liability Groups (JLGS), Self Help Groups (SHGS))                                                                                   6

In [93]:
merged_df["beneficiary_groups_normalized"] = merged_df["beneficiary_groups"].apply(lambda x: ", ".join(sorted(str(x).split(", "))) if pd.notna(x) else pd.NA)
print(merged_df["beneficiary_groups_normalized"].value_counts().head(30).to_string())

beneficiary_groups_normalized
Individual                                                                                                                                        3429
Business Entity                                                                                                                                    231
Family, Individual                                                                                                                                 141
Business Entity, Industries                                                                                                                        125
Family                                                                                                                                             119
Business Entity, Individual                                                                                                                         39
Registered Societies                                                                                                                                36
University / Institution                                                                                                                            34
All                                                                                                                                                 30
Industries                                                                                                                                          28
Artists                                                                                                                                             26
Business Entity, Individual, Registered Societies, Self Help Groups (SHGS)                                                                          26
Individual, Self Help Groups (SHGS)                                                                                                                 24
Individual, University / Institution                                                                                                                22
Individual, Registered Societies, Self Help Groups (SHGS)                                                                                           13
Self Help Groups (SHGS)                                                                                                                             13
Institution                                                                                                                                         12
NGO                                                                                                                                                 11
Business Entity, Individual, Industries                                                                                                             11
Sportsperson                                                                                                                                        11
Artists, Individual                                                                                                                                  9
Government Organisation                                                                                                                              9
Village                                                                                                                                              8
Business Entity, Government Organisation, Industries, Joint Liability Groups (JLGS), NGO, Registered Societies, Self Help Groups (SHGS), Trust       8
Business Entity, University / Institution                                                                                                            7
Individual, Registered Societies                                                                                                                     7
Journalist                                                                                                                                           7
Individual, Sportsperson                                                                                                                             6
Business Entity, Individual, Self Help Groups (SHGS)                                                                                                 6
Individual, Joint Liability Groups (JLGS), Self Help Groups (SHGS)                                                                                   6

In [94]:
merged_df["categories"] = merged_df["category_unified"].apply(lambda x: ", ".join(sorted(str(x).split(", "))) if pd.notna(x) else pd.NA)
print(merged_df["categories"].value_counts().head(30).to_string())

categories
Education & Learning                                                        727
Social Welfare & Empowerment                                                686
Agriculture & Rural Development                                             667
Business & Entrepreneurship                                                 417
Social Welfare & Empowerment, Women and Child                               188
Sports & Culture                                                            154
Education & Learning, Social Welfare & Empowerment                          129
Skills & Employment                                                         127
Health & Wellness                                                           124
Banking, Financial Services & Insurance                                      72
Banking, Business & Entrepreneurship, Financial Services & Insurance         71
Housing & Shelter                                                            65
Health & Wellness, Social Welfare & Empowerment                              55
Education & Learning, Women and Child                                        54
Business & Entrepreneurship, Skills & Employment                             50
Agriculture & Rural Development, Business & Entrepreneurship                 46
Women and Child                                                              45
IT & Communications, Science                                                 45
Health & Wellness, Women and Child                                           45
Skills & Employment, Social Welfare & Empowerment                            41
Social Welfare & Empowerment, Sports & Culture                               40
Agriculture & Rural Development, Banking, Financial Services & Insurance     36
Banking, Financial Services & Insurance, Social Welfare & Empowerment        36
Education & Learning, Skills & Employment                                    30
Travel & Tourism                                                             30
Education & Learning, IT & Communications, Science                           28
Housing & Shelter, Social Welfare & Empowerment                              25
Skills & Employment, Sports & Culture                                        23
Business & Entrepreneurship, Travel & Tourism                                23
Business & Entrepreneurship, Social Welfare & Empowerment                    22

In [95]:
merged_df["application_mode"] = merged_df["application_mode_unified"].replace({"Online & Offline": "Online + Offline", "Direct / Not Specified": "Direct / Not Specified"}).astype("string").str.strip()
print(merged_df["application_mode"].value_counts(dropna=False).to_string())

application_mode
<NA>                      2796
Online                     914
Offline                    868
Online + Offline           277
Direct / Not Specified       7

In [96]:
merged_df["tags_normalized"] = merged_df["raw_tags_unified"].apply(lambda x: ", ".join(sorted({t.strip() for t in str(x).split(",") if t.strip()})) if pd.notna(x) and str(x).strip() else pd.NA)
print(merged_df["tags_normalized"].dropna().head(10).to_string(index=False))

                                       Capital, Entrepreneur, Investment, Subsidy, Unemployed, Youth
                                              Chemicals, Dyes, Handloom, Hank, Subsidy, Weaver, Yarn
                               AICTE, Augmenting, Eastern, For, Grant, Infrastructure, North, Region
                                               Assistance, Child, Financial, Girl, Mother, Nutrition
Access, And, Development, Dissemination, For, Industry, Institution, Knowledge, Ministry, Proposa...
                               Below, Cashless, Health, Hospital, Line, Patients, Poverty, Treatment
AABCS, Ambedkar, Annal, Business, Caste, Champions, Entrepreneur, Loan, MSME, Scheduled, Subsidy,...
                                                              Bima, DBT, Incentive, Insurance, Labor
                                                       Abhinandan, Education, Loan, Student, Subsidy
                                                                                       Loan, Subsidy

In [97]:
print("Missing:", merged_df["tags_normalized"].isna().sum())
print("Unique:", merged_df["tags_normalized"].nunique())
print(merged_df["tags_normalized"].dropna().head(20).to_string(index=False))

Missing: 2812
Unique: 2020
                                       Capital, Entrepreneur, Investment, Subsidy, Unemployed, Youth
                                              Chemicals, Dyes, Handloom, Hank, Subsidy, Weaver, Yarn
                               AICTE, Augmenting, Eastern, For, Grant, Infrastructure, North, Region
                                               Assistance, Child, Financial, Girl, Mother, Nutrition
Access, And, Development, Dissemination, For, Industry, Institution, Knowledge, Ministry, Proposa...
                               Below, Cashless, Health, Hospital, Line, Patients, Poverty, Treatment
AABCS, Ambedkar, Annal, Business, Caste, Champions, Entrepreneur, Loan, MSME, Scheduled, Subsidy,...
                                                              Bima, DBT, Incentive, Insurance, Labor
                                                       Abhinandan, Education, Loan, Student, Subsidy
                                                                                       Loan, Subsidy
           Adhoc, Award, Cash, Caste, Grant, Incentive, Merit, Scheduled, Special, Student, Students
               Accidental, Arogya, Assistance, Case, Diseases, Financial, Hospital, Nidhi, Treatment
                                                      House, Loan, Scheduled, Social, Tribe, Welfare
                                                                         Farm, Farmer, Farming, Land
         Below, Bread, Destitute, Insurance, Line, Poverty, Security, Social, Welfare, Widow, Winner
            Academic, Agriculture, Graduate, Horticulture, Sponsorship, Student, Under, Universities
                                                      Community, Education, Free, Labor, Life, Skill
                           Assistance, Financial, Housing, Repair, Scheduled, Social, Tribe, Welfare
                                    Assistance, Beti, Child, Financial, Girl, Grant, Investment, LIC
                                                                        Agriculture, Farmer, Farming

In [98]:
eligibility_parts = ["eligibility_text","age_min_unified","age_max_unified","income_max_unified","gender_eligibility_unified","caste_category_unified","residence_requirement_unified","disability_eligibility_unified","bpl_required_unified"]
eligibility_labels = ["Eligibility","Minimum Age","Maximum Age","Maximum Income","Gender","Caste Category","Residence Requirement","Disability","BPL"]
merged_df["eligibility_text_final"] = merged_df[eligibility_parts].fillna("").astype(str).apply(lambda x: "\n".join(f"{k}: {v}" for k,v in zip(eligibility_labels,x) if v.strip() and v.strip().lower() != "nan"), axis=1)
print(merged_df["eligibility_text_final"].str.len().describe())

count    4862.000000
mean      778.279309
std       687.174286
min         0.000000
25%       391.250000
50%       589.500000
75%       912.000000
max      9348.000000
Name: eligibility_text_final, dtype: float64

In [99]:
text_map = {"Scheme Name":"scheme_name","Government Level":"government_level_unified","State/UT":"state_ut","Ministry":"ministry","Department":"department_unified","Category":"categories","Beneficiary":"beneficiary_groups_normalized","Application Mode":"application_mode","Description":"description","Benefits":"benefits_unified","Eligibility":"eligibility_text_final","Exclusions":"exclusion_text_unified","Application Process":"application_process_unified","Documents Required":"documents_required_unified","FAQs":"faqs_unified","Tags":"tags_normalized"}
merged_df["combined_text"] = merged_df[list(text_map.values())].fillna("").astype(str).apply(lambda x: "\n".join(f"{k}: {v}" for k,v in zip(text_map.keys(),x) if v.strip() and v.strip().lower() != "nan"), axis=1)
print(merged_df["combined_text"].str.len().describe())

count     4862.000000
mean      4785.122995
std       2895.921508
min        169.000000
25%       2708.250000
50%       4112.500000
75%       6150.500000
max      32473.000000
Name: combined_text, dtype: float64

In [100]:
print(merged_df.columns.tolist())

['scheme_slug_hf', 'scheme_name_hf', 'description_hf', 'ministry_hf', 'department', 'state_hf', 'category_hf', 'beneficiary_type_hf', 'benefits_hf', 'eligibility_text_hf', 'application_process_hf', 'documents_required_hf', 'apply_url', 'official_url_hf', 'age_min', 'age_max', 'gender_eligibility', 'caste_category', 'income_max', 'residence_requirement', 'eligibility_state', 'disability_eligibility', 'bpl_required', 'scraped_at', 'name_normalized_hf', 'scheme_id_hf', 'unified_scheme_id', 'scheme_name_github', 'scheme_slug_github', 'government_level', 'state_ut_ministry', 'application_mode', 'raw_tags', 'description_github', 'eligibility_criteria', 'eligibility_general', 'exclusion_text', 'benefits', 'application_process', 'documents_required', 'faqs', 'official_url_github', 'myscheme_url', 'name_normalized_github', 'scheme_id_github', '_merge', 'scheme_name', 'scheme_slug', 'scheme_id', 'government_level_unified', 'state_ut', 'ministry', 'department_unified', 'category_unified', 'beneficiary_groups', 'application_mode_unified', 'raw_tags_unified', 'description', 'benefits_unified', 'eligibility_text', 'exclusion_text_unified', 'application_process_unified', 'documents_required_unified', 'faqs_unified', 'official_url', 'myscheme_url_unified', 'apply_url_unified', 'age_min_unified', 'age_max_unified', 'income_max_unified', 'gender_eligibility_unified', 'caste_category_unified', 'residence_requirement_unified', 'disability_eligibility_unified', 'bpl_required_unified', 'scraped_at_unified', 'source_hf', 'source_github', 'source_count', 'source', 'combined_text', 'beneficiary_groups_normalized', 'categories', 'tags_normalized', 'eligibility_text_final']

In [101]:
final_cols = ["scheme_id","scheme_name","scheme_slug","government_level_unified","state_ut","ministry","department_unified","categories","beneficiary_groups_normalized","age_min_unified","age_max_unified","income_max_unified","gender_eligibility_unified","caste_category_unified","residence_requirement_unified","disability_eligibility_unified","bpl_required_unified","eligibility_text_final","exclusion_text_unified","description","benefits_unified","application_mode","application_process_unified","documents_required_unified","faqs_unified","tags_normalized","official_url","myscheme_url_unified","apply_url_unified","source_hf","source_github","source_count","source","scraped_at_unified","combined_text"]
print("Final columns:", len(final_cols))
print("\nMissing columns:", [c for c in final_cols if c not in merged_df.columns])

Final columns: 35

Missing columns: []

In [102]:
final_df = merged_df[final_cols].copy()
print(final_df.shape)
print(final_df.head(2).to_string())

(4862, 35)
  scheme_id                                     scheme_name scheme_slug government_level_unified        state_ut ministry                            department_unified           categories beneficiary_groups_normalized  age_min_unified  age_max_unified  income_max_unified gender_eligibility_unified caste_category_unified residence_requirement_unified disability_eligibility_unified bpl_required_unified                                                                                                                                                                                                                                                    eligibility_text_final exclusion_text_unified                                                                                                                                                                                                                                           description                                                                                                                                                                                                                          benefits_unified application_mode                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  application_process_unified                                                                                                              documents_required_unified faqs_unified tags_normalized                                  official_url myscheme_url_unified                                                             apply_url_unified  source_hf  source_github  source_count source          scraped_at_unified                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        combined_text
0  108easuk  108, Emergency Ambulance Service - Uttarakhand    108easuk                 State/UT     Uttarakhand     <NA>  Medical Health And Family Welfare Department    Health & Wellness                    Individual              NaN              NaN                 NaN                        all                     []                          both                          False                False  Eligibility: 1. The beneficiary must be a resident of Uttarakhand.\n   1. The benefit is provided to accident victims and individuals requiring emergency services.\n\n<br>\nGender: all\nCaste Category: []\nResidence Requirement: both\nDisability: False\nBPL: False                                                                The scheme aims to provide timely emergency medical assistance by transporting patients to hospitals and offering essential first aid through a free, state-wide ambulance service accessible by calling 108.  - In any type of medical emergency, patients are transported to the hospital and provided with first aid facilities. \n  - The benefits of this service are being provided to the residents of the state through 272 ambulances.\n\n<br>             <NA>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          [Offline]\nThe services can be availed free of cost by calling 108.                                           Identity proof of the patient\nMedical report, if any\nOther supporting documents as required                         <NA>  https://www.myscheme.gov.in/schemes/108easuk                 <NA>      https://uk.gov.in/department92/library_file/file-04-12-2023-06-02-23.pdf       True          False             1     HF  2026-07-05 09:34:54.298+00                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Scheme Name: 108, Emergency Ambulance Service - Uttarakhand\nGovernment Level: State/UT\nState/UT: Uttarakhand\nDepartment: Medical Health And Family Welfare Department\nCategory: Health & Wellness\nBeneficiary: Individual\nDescription: The scheme aims to provide timely emergency medical assistance by transporting patients to hospitals and offering essential first aid through a free, state-wide ambulance service accessible by calling 108.\nBenefits: - In any type of medical emergency, patients are transported to the hospital and provided with first aid facilities. \n  - The benefits of this service are being provided to the residents of the state through 272 ambulances.\n\n<br>\nEligibility: Eligibility: 1. The beneficiary must be a resident of Uttarakhand.\n   1. The benefit is provided to accident victims and individuals requiring emergency services.\n\n<br>\nGender: all\nCaste Category: []\nResidence Requirement: both\nDisability: False\nBPL: False\nApplication Process: [Offline]\nThe services can be availed free of cost by calling 108.\nDocuments Required: Identity proof of the patient\nMedical report, if any\nOther supporting documents as required
1   15dsugt             15 Days Skill Up-gradation Training     15dsugt                 State/UT  Andhra Pradesh     <NA>                             Labour Department  Skills & Employment                    Individual              NaN              NaN                 NaN                        all                     []                          both                          False                False                      Eligibility: - The applicant should be a registered construction worker under the Andhra Pradesh Building and Other Construction Workers Welfare Board.\nGender: all\nCaste Category: []\nResidence Requirement: both\nDisability: False\nBPL: False                         The "15 Days Skill Up-gradation Training" scheme aims to provide skill training, safety, and hygiene education for building and other construction workers registered with the Andhra Pradesh Building and Other Construction Workers Welfare Board.                                                                                                                    - Stipend of ₹7,000/-. \n\n- Skill development training for construction workers.\n- Tool kits provided post-training.             <NA>  [Offline]\nStep-1: The interested applicant should visit (during office hours) the A.P. Building & Other Construction Workers Welfare Board and request a hard copy of the prescribed format of the application form from the staff exclusively entrusted to issue and collect filled-in applications.\nStep-2: In the application form, fill in all the mandatory fields, and attach copies of all the mandatory documents (self-attest, if required).\nStep-3: Submit the duly filled and signed application form along with the documents to the Assistant Labour Officer/Assistant Commissioner of Labour.\nStep-4: Request a receipt or acknowledgement from the Assistant Labour Officer/Assistant Commissioner of Labour to whom the application has been submitted. Ensure that the receipt contains essential details such as the date and time of submission, and a unique identification number (if applicable).  Aadhaar Card of the Worker.\nRegistration Certificate with the Welfare Board.\nBank Account Details.\nAny Other Documents if required.                         <NA>   https://www.myscheme.gov.in/schemes/15dsugt                 <NA>  https://apbocwwb.ap.nic.in/APBOCWW3/G.O.ms.No.43,dated.2013,NAC_Training.pdf       True          False             1     HF  2026-07-05 09:48:05.743+00  Scheme Name: 15 Days Skill Up-gradation Training\nGovernment Level: State/UT\nState/UT: Andhra Pradesh\nDepartment: Labour Department\nCategory: Skills & Employment\nBeneficiary: Individual\nDescription: The "15 Days Skill Up-gradation Training" scheme aims to provide skill training, safety, and hygiene education for building and other construction workers registered with the Andhra Pradesh Building and Other Construction Workers Welfare Board.\nBenefits: - Stipend of ₹7,000/-. \n\n- Skill development training for construction workers.\n- Tool kits provided post-training.\nEligibility: Eligibility: - The applicant should be a registered construction worker under the Andhra Pradesh Building and Other Construction Workers Welfare Board.\nGender: all\nCaste Category: []\nResidence Requirement: both\nDisability: False\nBPL: False\nApplication Process: [Offline]\nStep-1: The interested applicant should visit (during office hours) the A.P. Building & Other Construction Workers Welfare Board and request a hard copy of the prescribed format of the application form from the staff exclusively entrusted to issue and collect filled-in applications.\nStep-2: In the application form, fill in all the mandatory fields, and attach copies of all the mandatory documents (self-attest, if required).\nStep-3: Submit the duly filled and signed application form along with the documents to the Assistant Labour Officer/Assistant Commissioner of Labour.\nStep-4: Request a receipt or acknowledgement from the Assistant Labour Officer/Assistant Commissioner of Labour to whom the application has been submitted. Ensure that the receipt contains essential details such as the date and time of submission, and a unique identification number (if applicable).\nDocuments Required: Aadhaar Card of the Worker.\nRegistration Certificate with the Welfare Board.\nBank Account Details.\nAny Other Documents if required.

In [103]:
core_cols = ["scheme_id","scheme_name","government_level_unified","description","benefits_unified","eligibility_text_final","official_url","combined_text"]
print("Shape:", final_df.shape)
print("Duplicate IDs:", final_df["scheme_id"].duplicated().sum())
print("Duplicate names:", final_df["scheme_name"].duplicated().sum())
print("Duplicate combined_text:", final_df["combined_text"].duplicated().sum())
print("Missing core fields:\n", final_df[core_cols].isna().sum().to_string())

Shape: (4862, 35)
Duplicate IDs: 0
Duplicate names: 0
Duplicate combined_text: 0
Missing core fields:
 scheme_id                   0
scheme_name                 0
government_level_unified    0
description                 0
benefits_unified            0
eligibility_text_final      0
official_url                0
combined_text               0

In [104]:
print(final_df.dtypes.to_string())

scheme_id                                 object
scheme_name                               object
scheme_slug                               object
government_level_unified                  object
state_ut                          string[python]
ministry                          string[python]
department_unified                string[python]
categories                                object
beneficiary_groups_normalized             object
age_min_unified                          float64
age_max_unified                          float64
income_max_unified                       float64
gender_eligibility_unified        string[python]
caste_category_unified            string[python]
residence_requirement_unified     string[python]
disability_eligibility_unified    string[python]
bpl_required_unified              string[python]
eligibility_text_final                    object
exclusion_text_unified            string[python]
description                               object
benefits_unified                          object
application_mode                  string[python]
application_process_unified               object
documents_required_unified                object
faqs_unified                      string[python]
tags_normalized                           object
official_url                              object
myscheme_url_unified              string[python]
apply_url_unified                 string[python]
source_hf                                   bool
source_github                               bool
source_count                               int64
source                                    object
scraped_at_unified                string[python]
combined_text                             object

In [105]:
final_df.to_csv("/content/government_schemes_final.csv", index=False)
print("Saved:", final_df.shape)

Saved: (4862, 35)